source 'ssh://git@szgitlab.youxin.com:222/YXPods/YXSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'YXKit_Example' do
  pod 'YXKit', :path => '../YXKit.podspec'

  #pod 'YYModel'
  #pod 'YXKit/YXConstant'
  #pod 'YXKit/YXSnapKit'

  target 'YXKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
