// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capflow.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum OBJECT_QUOTECapFlowType

typedef GPB_ENUM(OBJECT_QUOTECapFlowType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTECapFlowType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  OBJECT_QUOTECapFlowType_OneDay = 0,
  OBJECT_QUOTECapFlowType_FiveDay = 1,
};

GPBEnumDescriptor *OBJECT_QUOTECapFlowType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTECapFlowType_IsValidValue(int32_t value);

#pragma mark - OBJECT_QUOTECapflowRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OBJECT_QUOTECapflowRoot : GPBRootObject
@end

#pragma mark - OBJECT_QUOTECapFlowData

typedef GPB_ENUM(OBJECT_QUOTECapFlowData_FieldNumber) {
  OBJECT_QUOTECapFlowData_FieldNumber_Time = 1,
  OBJECT_QUOTECapFlowData_FieldNumber_Total = 2,
  OBJECT_QUOTECapFlowData_FieldNumber_Bin = 3,
  OBJECT_QUOTECapFlowData_FieldNumber_Min = 4,
  OBJECT_QUOTECapFlowData_FieldNumber_Sin = 5,
  OBJECT_QUOTECapFlowData_FieldNumber_Bout = 6,
  OBJECT_QUOTECapFlowData_FieldNumber_Mout = 7,
  OBJECT_QUOTECapFlowData_FieldNumber_Sout = 8,
  OBJECT_QUOTECapFlowData_FieldNumber_Netbin = 9,
  OBJECT_QUOTECapFlowData_FieldNumber_Netmin = 10,
  OBJECT_QUOTECapFlowData_FieldNumber_Netsin = 11,
  OBJECT_QUOTECapFlowData_FieldNumber_In_p = 12,
  OBJECT_QUOTECapFlowData_FieldNumber_Out_p = 13,
  OBJECT_QUOTECapFlowData_FieldNumber_Netin = 14,
  OBJECT_QUOTECapFlowData_FieldNumber_Binprop = 15,
  OBJECT_QUOTECapFlowData_FieldNumber_Minprop = 16,
  OBJECT_QUOTECapFlowData_FieldNumber_Sinprop = 17,
  OBJECT_QUOTECapFlowData_FieldNumber_Boutprop = 18,
  OBJECT_QUOTECapFlowData_FieldNumber_Moutprop = 19,
  OBJECT_QUOTECapFlowData_FieldNumber_Soutprop = 20,
  OBJECT_QUOTECapFlowData_FieldNumber_PriceBase = 21,
};

GPB_FINAL @interface OBJECT_QUOTECapFlowData : GPBMessage

/** 资金流向的时间  YYYYMMDDHHMM */
@property(nonatomic, readwrite) uint64_t time;

/** 总成交额 */
@property(nonatomic, readwrite) int64_t total;

/** 流入大单金额 */
@property(nonatomic, readwrite) int64_t bin;

/** 流入中单金额 */
@property(nonatomic, readwrite) int64_t min;

/** 流入小单金额 */
@property(nonatomic, readwrite) int64_t sin;

/** 流出大单金额 */
@property(nonatomic, readwrite) int64_t bout;

/** 流出中单金额 */
@property(nonatomic, readwrite) int64_t mout;

/** 流出小单金额 */
@property(nonatomic, readwrite) int64_t sout;

/** 净流入大单金额 */
@property(nonatomic, readwrite) int64_t netbin;

/** 净流入中单金额 */
@property(nonatomic, readwrite) int64_t netmin;

/** 净流入小单金额 */
@property(nonatomic, readwrite) int64_t netsin;

/** 流入总金额 */
@property(nonatomic, readwrite) int64_t in_p;

/** 流出总金额 */
@property(nonatomic, readwrite) int64_t out_p;

/** 净流入总金额 */
@property(nonatomic, readwrite) int64_t netin;

/** 流入大单金额占比, 使用时除100 */
@property(nonatomic, readwrite) int32_t binprop;

/** 流入中单金额占比, 使用时除100 */
@property(nonatomic, readwrite) int32_t minprop;

/** 流入小单金额占比, 使用时除100 */
@property(nonatomic, readwrite) int32_t sinprop;

/** 流出大单金额占比, 使用时除100 */
@property(nonatomic, readwrite) int32_t boutprop;

/** 流出中单金额占比, 使用时除100 */
@property(nonatomic, readwrite) int32_t moutprop;

/** 流程小单金额占比, 使用时除100 */
@property(nonatomic, readwrite) int32_t soutprop;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@end

#pragma mark - OBJECT_QUOTECapNetData

typedef GPB_ENUM(OBJECT_QUOTECapNetData_FieldNumber) {
  OBJECT_QUOTECapNetData_FieldNumber_Time = 1,
  OBJECT_QUOTECapNetData_FieldNumber_In_p = 2,
  OBJECT_QUOTECapNetData_FieldNumber_Out_p = 3,
  OBJECT_QUOTECapNetData_FieldNumber_Netin = 4,
};

GPB_FINAL @interface OBJECT_QUOTECapNetData : GPBMessage

/** 资金净流入的时间  YYYYMMDDHHMM */
@property(nonatomic, readwrite) uint64_t time;

/** 流入金额 */
@property(nonatomic, readwrite) int64_t in_p;

/** 流出金额 */
@property(nonatomic, readwrite) int64_t out_p;

/** 净流入金额 */
@property(nonatomic, readwrite) int64_t netin;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
