// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cryptosmeta.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(OBJECT_MARKETExchange);
GPB_ENUM_FWD_DECLARE(OBJECT_MARKETMarketId);
GPB_ENUM_FWD_DECLARE(OBJECT_SECUListStatus);
GPB_ENUM_FWD_DECLARE(OBJECT_SECUSecuType1);
GPB_ENUM_FWD_DECLARE(OBJECT_SECUSecuType2);
GPB_ENUM_FWD_DECLARE(OBJECT_SECUSecuType3);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - OBJECT_SECUCryptosmetaRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OBJECT_SECUCryptosmetaRoot : GPBRootObject
@end

#pragma mark - OBJECT_SECUCryptosBasicMeta

typedef GPB_ENUM(OBJECT_SECUCryptosBasicMeta_FieldNumber) {
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuCode = 1,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuCodeTrade = 2,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuMarket = 3,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_Exchange = 4,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_BaseAsset = 5,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_QuoteAsset = 6,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_BasePrecision = 7,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_QuotePrecision = 8,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuChinName = 9,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuChinNameAbbr = 10,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuEngName = 11,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SecuTraditionAbbr = 12,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_ListedState = 13,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_Type1 = 14,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_Type2 = 15,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_Type3 = 16,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_Week52High = 20,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_Week52Low = 21,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SymbolDisplay = 24,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_IconURL = 25,
  OBJECT_SECUCryptosBasicMeta_FieldNumber_SortWeight = 26,
};

GPB_FINAL @interface OBJECT_SECUCryptosBasicMeta : GPBMessage

/** name for symbol.exchangestr */
@property(nonatomic, readwrite, copy, null_resettable) NSString *secuCode;

/** exchange symbol */
@property(nonatomic, readwrite, copy, null_resettable) NSString *secuCodeTrade;

/** market, default cryptos enum */
@property(nonatomic, readwrite) enum OBJECT_MARKETMarketId secuMarket;

/** binance enum etc.. */
@property(nonatomic, readwrite) enum OBJECT_MARKETExchange exchange;

/** base asset */
@property(nonatomic, readwrite, copy, null_resettable) NSString *baseAsset;

/** quote for trading basse asset */
@property(nonatomic, readwrite, copy, null_resettable) NSString *quoteAsset;

/** desc quote data for base asset precision */
@property(nonatomic, readwrite) int32_t basePrecision;

/** desc quote data for quote asset precision */
@property(nonatomic, readwrite) int32_t quotePrecision;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secuChinName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secuChinNameAbbr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secuEngName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secuTraditionAbbr;

@property(nonatomic, readwrite) enum OBJECT_SECUListStatus listedState;

/** 证券一级分类 */
@property(nonatomic, readwrite) enum OBJECT_SECUSecuType1 type1;

/** 证券二级分类 */
@property(nonatomic, readwrite) enum OBJECT_SECUSecuType2 type2;

/** 证券三级分类 */
@property(nonatomic, readwrite) enum OBJECT_SECUSecuType3 type3;

/** string 8位小数 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *week52High;

@property(nonatomic, readwrite, copy, null_resettable) NSString *week52Low;

/** 符号展示 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbolDisplay;

@property(nonatomic, readwrite, copy, null_resettable) NSString *iconURL;

@property(nonatomic, readwrite) int32_t sortWeight;

@end

/**
 * Fetches the raw value of a @c OBJECT_SECUCryptosBasicMeta's @c secuMarket property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_SECUCryptosBasicMeta_SecuMarket_RawValue(OBJECT_SECUCryptosBasicMeta *message);
/**
 * Sets the raw value of an @c OBJECT_SECUCryptosBasicMeta's @c secuMarket property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_SECUCryptosBasicMeta_SecuMarket_RawValue(OBJECT_SECUCryptosBasicMeta *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_SECUCryptosBasicMeta's @c exchange property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_SECUCryptosBasicMeta_Exchange_RawValue(OBJECT_SECUCryptosBasicMeta *message);
/**
 * Sets the raw value of an @c OBJECT_SECUCryptosBasicMeta's @c exchange property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_SECUCryptosBasicMeta_Exchange_RawValue(OBJECT_SECUCryptosBasicMeta *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_SECUCryptosBasicMeta's @c listedState property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_SECUCryptosBasicMeta_ListedState_RawValue(OBJECT_SECUCryptosBasicMeta *message);
/**
 * Sets the raw value of an @c OBJECT_SECUCryptosBasicMeta's @c listedState property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_SECUCryptosBasicMeta_ListedState_RawValue(OBJECT_SECUCryptosBasicMeta *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_SECUCryptosBasicMeta's @c type1 property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_SECUCryptosBasicMeta_Type1_RawValue(OBJECT_SECUCryptosBasicMeta *message);
/**
 * Sets the raw value of an @c OBJECT_SECUCryptosBasicMeta's @c type1 property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_SECUCryptosBasicMeta_Type1_RawValue(OBJECT_SECUCryptosBasicMeta *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_SECUCryptosBasicMeta's @c type2 property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_SECUCryptosBasicMeta_Type2_RawValue(OBJECT_SECUCryptosBasicMeta *message);
/**
 * Sets the raw value of an @c OBJECT_SECUCryptosBasicMeta's @c type2 property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_SECUCryptosBasicMeta_Type2_RawValue(OBJECT_SECUCryptosBasicMeta *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_SECUCryptosBasicMeta's @c type3 property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_SECUCryptosBasicMeta_Type3_RawValue(OBJECT_SECUCryptosBasicMeta *message);
/**
 * Sets the raw value of an @c OBJECT_SECUCryptosBasicMeta's @c type3 property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_SECUCryptosBasicMeta_Type3_RawValue(OBJECT_SECUCryptosBasicMeta *message, int32_t value);

#pragma mark - OBJECT_SECUCryptosParserExchangeInfoData

typedef GPB_ENUM(OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber) {
  OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber_Symbol = 1,
  OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber_Status = 2,
  OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber_BaseAsset = 3,
  OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber_QuoteAsset = 4,
  OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber_BasePrecision = 5,
  OBJECT_SECUCryptosParserExchangeInfoData_FieldNumber_QuotePrecision = 6,
};

GPB_FINAL @interface OBJECT_SECUCryptosParserExchangeInfoData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *baseAsset;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quoteAsset;

@property(nonatomic, readwrite) int32_t basePrecision;

@property(nonatomic, readwrite) int32_t quotePrecision;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
