// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class API_CLIENTCapFlowPush;
@class API_CLIENTCapNetPush;
@class API_CLIENTError;
@class API_CLIENTKLPush;
@class API_CLIENTMSPush;
@class API_CLIENTOrderBookPush;
@class API_CLIENTQuotePush;
@class API_CLIENTRTPush;
@class API_CLIENTTKPush;
@class API_CLIENTTSPush;
@class OBJECT_MARKETStatus;
@class OBJECT_QUOTECapFlowData;
@class OBJECT_QUOTECapNetData;
@class OBJECT_QUOTECryptosKline;
@class OBJECT_QUOTECryptosQuote;
@class OBJECT_QUOTECryptosTick;
@class OBJECT_QUOTECryptosTimeline;
@class OBJECT_QUOTEKLineData;
@class OBJECT_QUOTEOrderBook;
@class OBJECT_QUOTEQuote;
@class OBJECT_QUOTETSData;
@class OBJECT_QUOTETickData;
@class OBJECT_SECUFullID;
GPB_ENUM_FWD_DECLARE(OBJECT_QUOTECapFlowType);
GPB_ENUM_FWD_DECLARE(OBJECT_QUOTEKLineDirection);
GPB_ENUM_FWD_DECLARE(OBJECT_QUOTEKLineType);
GPB_ENUM_FWD_DECLARE(OBJECT_QUOTEQuoteScene);
GPB_ENUM_FWD_DECLARE(OBJECT_QUOTEQuoteType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum API_CLIENTPushType

typedef GPB_ENUM(API_CLIENTPushType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  API_CLIENTPushType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  API_CLIENTPushType_None = 0,
  API_CLIENTPushType_Rt = 1,
  API_CLIENTPushType_Ts = 2,
  API_CLIENTPushType_Tk = 4,
  API_CLIENTPushType_Kl = 8,
  API_CLIENTPushType_Ms = 16,
  API_CLIENTPushType_Cap = 32,
  API_CLIENTPushType_Cn = 64,
  API_CLIENTPushType_Tspre = 128,
  API_CLIENTPushType_Tsafter = 256,
  API_CLIENTPushType_Tkpre = 512,
  API_CLIENTPushType_Tkafter = 1024,
  API_CLIENTPushType_Ob = 2048,
  API_CLIENTPushType_Obchart = 4096,
};

GPBEnumDescriptor *API_CLIENTPushType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL API_CLIENTPushType_IsValidValue(int32_t value);

#pragma mark - Enum API_CLIENTPushDataType

typedef GPB_ENUM(API_CLIENTPushDataType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  API_CLIENTPushDataType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 普通数据，辉立暗盘 */
  API_CLIENTPushDataType_Normal = 0,

  /** 加密货币 */
  API_CLIENTPushDataType_Cryptos = 1,

  /** 富途暗盘 */
  API_CLIENTPushDataType_Futu = 2,

  /** 全美综合报价 */
  API_CLIENTPushDataType_Uscomp = 3,
};

GPBEnumDescriptor *API_CLIENTPushDataType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL API_CLIENTPushDataType_IsValidValue(int32_t value);

#pragma mark - API_CLIENTPushRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface API_CLIENTPushRoot : GPBRootObject
@end

#pragma mark - API_CLIENTSub

typedef GPB_ENUM(API_CLIENTSub_FieldNumber) {
  API_CLIENTSub_FieldNumber_TopicArray = 1,
};

GPB_FINAL @interface API_CLIENTSub : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *topicArray;
/** The number of items in @c topicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger topicArray_Count;

@end

#pragma mark - API_CLIENTSubRsp

typedef GPB_ENUM(API_CLIENTSubRsp_FieldNumber) {
  API_CLIENTSubRsp_FieldNumber_Error = 1,
};

GPB_FINAL @interface API_CLIENTSubRsp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTError *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

@end

#pragma mark - API_CLIENTUnSub

typedef GPB_ENUM(API_CLIENTUnSub_FieldNumber) {
  API_CLIENTUnSub_FieldNumber_TopicArray = 1,
};

GPB_FINAL @interface API_CLIENTUnSub : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *topicArray;
/** The number of items in @c topicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger topicArray_Count;

@end

#pragma mark - API_CLIENTUnSubRsp

typedef GPB_ENUM(API_CLIENTUnSubRsp_FieldNumber) {
  API_CLIENTUnSubRsp_FieldNumber_Error = 1,
};

GPB_FINAL @interface API_CLIENTUnSubRsp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTError *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

@end

#pragma mark - API_CLIENTAcAuthReq

typedef GPB_ENUM(API_CLIENTAcAuthReq_FieldNumber) {
  API_CLIENTAcAuthReq_FieldNumber_AccessToken = 1,
};

GPB_FINAL @interface API_CLIENTAcAuthReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@end

#pragma mark - API_CLIENTAcAuthRsp

typedef GPB_ENUM(API_CLIENTAcAuthRsp_FieldNumber) {
  API_CLIENTAcAuthRsp_FieldNumber_Error = 1,
  API_CLIENTAcAuthRsp_FieldNumber_AuthBitmap = 2,
  API_CLIENTAcAuthRsp_FieldNumber_RepeatAuth = 3,
};

GPB_FINAL @interface API_CLIENTAcAuthRsp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTError *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

@property(nonatomic, readwrite) uint32_t authBitmap;

@property(nonatomic, readwrite) BOOL repeatAuth;

@end

#pragma mark - API_CLIENTPush

typedef GPB_ENUM(API_CLIENTPush_FieldNumber) {
  API_CLIENTPush_FieldNumber_Topic = 1,
  API_CLIENTPush_FieldNumber_QuoteArray = 2,
};

GPB_FINAL @interface API_CLIENTPush : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *topic;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<API_CLIENTQuotePush*> *quoteArray;
/** The number of items in @c quoteArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger quoteArray_Count;

@end

#pragma mark - API_CLIENTQuotePush

typedef GPB_ENUM(API_CLIENTQuotePush_FieldNumber) {
  API_CLIENTQuotePush_FieldNumber_Type = 1,
  API_CLIENTQuotePush_FieldNumber_Rt = 2,
  API_CLIENTQuotePush_FieldNumber_Ts = 3,
  API_CLIENTQuotePush_FieldNumber_Tk = 4,
  API_CLIENTQuotePush_FieldNumber_Kl = 5,
  API_CLIENTQuotePush_FieldNumber_Ms = 6,
  API_CLIENTQuotePush_FieldNumber_Cap = 7,
  API_CLIENTQuotePush_FieldNumber_Cn = 8,
  API_CLIENTQuotePush_FieldNumber_Ob = 9,
};

GPB_FINAL @interface API_CLIENTQuotePush : GPBMessage

@property(nonatomic, readwrite) API_CLIENTPushType type;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTRTPush *rt;
/** Test to see if @c rt has been set. */
@property(nonatomic, readwrite) BOOL hasRt;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTTSPush *ts;
/** Test to see if @c ts has been set. */
@property(nonatomic, readwrite) BOOL hasTs;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTTKPush *tk;
/** Test to see if @c tk has been set. */
@property(nonatomic, readwrite) BOOL hasTk;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTKLPush *kl;
/** Test to see if @c kl has been set. */
@property(nonatomic, readwrite) BOOL hasKl;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTMSPush *ms;
/** Test to see if @c ms has been set. */
@property(nonatomic, readwrite) BOOL hasMs;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTCapFlowPush *cap;
/** Test to see if @c cap has been set. */
@property(nonatomic, readwrite) BOOL hasCap;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTCapNetPush *cn;
/** Test to see if @c cn has been set. */
@property(nonatomic, readwrite) BOOL hasCn;

@property(nonatomic, readwrite, strong, null_resettable) API_CLIENTOrderBookPush *ob;
/** Test to see if @c ob has been set. */
@property(nonatomic, readwrite) BOOL hasOb;

@end

/**
 * Fetches the raw value of a @c API_CLIENTQuotePush's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTQuotePush_Type_RawValue(API_CLIENTQuotePush *message);
/**
 * Sets the raw value of an @c API_CLIENTQuotePush's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTQuotePush_Type_RawValue(API_CLIENTQuotePush *message, int32_t value);

#pragma mark - API_CLIENTRTPush

typedef GPB_ENUM(API_CLIENTRTPush_FieldNumber) {
  API_CLIENTRTPush_FieldNumber_Scene = 1,
  API_CLIENTRTPush_FieldNumber_CustomFlag = 2,
  API_CLIENTRTPush_FieldNumber_Quote = 3,
  API_CLIENTRTPush_FieldNumber_SendTime = 4,
  API_CLIENTRTPush_FieldNumber_DataType = 5,
  API_CLIENTRTPush_FieldNumber_CryptosData = 6,
};

GPB_FINAL @interface API_CLIENTRTPush : GPBMessage

/** TODO [default = QS_FULL]; */
@property(nonatomic, readwrite) enum OBJECT_QUOTEQuoteScene scene;

/** 数据字段位图 */
@property(nonatomic, readwrite) uint64_t customFlag;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEQuote *quote;
/** Test to see if @c quote has been set. */
@property(nonatomic, readwrite) BOOL hasQuote;

@property(nonatomic, readwrite) uint64_t sendTime;

@property(nonatomic, readwrite) API_CLIENTPushDataType dataType;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECryptosQuote *cryptosData;
/** Test to see if @c cryptosData has been set. */
@property(nonatomic, readwrite) BOOL hasCryptosData;

@end

/**
 * Fetches the raw value of a @c API_CLIENTRTPush's @c scene property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTRTPush_Scene_RawValue(API_CLIENTRTPush *message);
/**
 * Sets the raw value of an @c API_CLIENTRTPush's @c scene property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTRTPush_Scene_RawValue(API_CLIENTRTPush *message, int32_t value);

/**
 * Fetches the raw value of a @c API_CLIENTRTPush's @c dataType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTRTPush_DataType_RawValue(API_CLIENTRTPush *message);
/**
 * Sets the raw value of an @c API_CLIENTRTPush's @c dataType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTRTPush_DataType_RawValue(API_CLIENTRTPush *message, int32_t value);

#pragma mark - API_CLIENTTSPush

typedef GPB_ENUM(API_CLIENTTSPush_FieldNumber) {
  API_CLIENTTSPush_FieldNumber_Id_p = 1,
  API_CLIENTTSPush_FieldNumber_PriceBase = 2,
  API_CLIENTTSPush_FieldNumber_Data_p = 3,
  API_CLIENTTSPush_FieldNumber_SendTime = 4,
  API_CLIENTTSPush_FieldNumber_DataType = 5,
  API_CLIENTTSPush_FieldNumber_CryptosData = 6,
};

GPB_FINAL @interface API_CLIENTTSPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTETSData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) uint64_t sendTime;

@property(nonatomic, readwrite) API_CLIENTPushDataType dataType;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECryptosTimeline *cryptosData;
/** Test to see if @c cryptosData has been set. */
@property(nonatomic, readwrite) BOOL hasCryptosData;

@end

/**
 * Fetches the raw value of a @c API_CLIENTTSPush's @c dataType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTTSPush_DataType_RawValue(API_CLIENTTSPush *message);
/**
 * Sets the raw value of an @c API_CLIENTTSPush's @c dataType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTTSPush_DataType_RawValue(API_CLIENTTSPush *message, int32_t value);

#pragma mark - API_CLIENTTKPush

typedef GPB_ENUM(API_CLIENTTKPush_FieldNumber) {
  API_CLIENTTKPush_FieldNumber_Id_p = 1,
  API_CLIENTTKPush_FieldNumber_PriceBase = 2,
  API_CLIENTTKPush_FieldNumber_Data_p = 3,
  API_CLIENTTKPush_FieldNumber_SendTime = 4,
  API_CLIENTTKPush_FieldNumber_DataType = 5,
  API_CLIENTTKPush_FieldNumber_CryptosData = 6,
};

GPB_FINAL @interface API_CLIENTTKPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTETickData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) uint64_t sendTime;

@property(nonatomic, readwrite) API_CLIENTPushDataType dataType;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECryptosTick *cryptosData;
/** Test to see if @c cryptosData has been set. */
@property(nonatomic, readwrite) BOOL hasCryptosData;

@end

/**
 * Fetches the raw value of a @c API_CLIENTTKPush's @c dataType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTTKPush_DataType_RawValue(API_CLIENTTKPush *message);
/**
 * Sets the raw value of an @c API_CLIENTTKPush's @c dataType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTTKPush_DataType_RawValue(API_CLIENTTKPush *message, int32_t value);

#pragma mark - API_CLIENTKLPush

typedef GPB_ENUM(API_CLIENTKLPush_FieldNumber) {
  API_CLIENTKLPush_FieldNumber_Id_p = 1,
  API_CLIENTKLPush_FieldNumber_Type = 2,
  API_CLIENTKLPush_FieldNumber_Direction = 3,
  API_CLIENTKLPush_FieldNumber_PriceBase = 5,
  API_CLIENTKLPush_FieldNumber_Data_p = 6,
  API_CLIENTKLPush_FieldNumber_SendTime = 7,
  API_CLIENTKLPush_FieldNumber_QuoteTime = 8,
  API_CLIENTKLPush_FieldNumber_DataType = 9,
  API_CLIENTKLPush_FieldNumber_CryptosData = 10,
};

GPB_FINAL @interface API_CLIENTKLPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite) enum OBJECT_QUOTEKLineType type;

/** TODO [default = KD_NONE]; */
@property(nonatomic, readwrite) enum OBJECT_QUOTEKLineDirection direction;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEKLineData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) uint64_t sendTime;

@property(nonatomic, readwrite) uint64_t quoteTime;

@property(nonatomic, readwrite) API_CLIENTPushDataType dataType;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECryptosKline *cryptosData;
/** Test to see if @c cryptosData has been set. */
@property(nonatomic, readwrite) BOOL hasCryptosData;

@end

/**
 * Fetches the raw value of a @c API_CLIENTKLPush's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTKLPush_Type_RawValue(API_CLIENTKLPush *message);
/**
 * Sets the raw value of an @c API_CLIENTKLPush's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTKLPush_Type_RawValue(API_CLIENTKLPush *message, int32_t value);

/**
 * Fetches the raw value of a @c API_CLIENTKLPush's @c direction property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTKLPush_Direction_RawValue(API_CLIENTKLPush *message);
/**
 * Sets the raw value of an @c API_CLIENTKLPush's @c direction property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTKLPush_Direction_RawValue(API_CLIENTKLPush *message, int32_t value);

/**
 * Fetches the raw value of a @c API_CLIENTKLPush's @c dataType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTKLPush_DataType_RawValue(API_CLIENTKLPush *message);
/**
 * Sets the raw value of an @c API_CLIENTKLPush's @c dataType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTKLPush_DataType_RawValue(API_CLIENTKLPush *message, int32_t value);

#pragma mark - API_CLIENTMSPush

typedef GPB_ENUM(API_CLIENTMSPush_FieldNumber) {
  API_CLIENTMSPush_FieldNumber_Status = 1,
};

GPB_FINAL @interface API_CLIENTMSPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_MARKETStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@end

#pragma mark - API_CLIENTCapFlowPush

typedef GPB_ENUM(API_CLIENTCapFlowPush_FieldNumber) {
  API_CLIENTCapFlowPush_FieldNumber_Id_p = 1,
  API_CLIENTCapFlowPush_FieldNumber_Type = 2,
  API_CLIENTCapFlowPush_FieldNumber_PriceBase = 3,
  API_CLIENTCapFlowPush_FieldNumber_Capflow = 4,
};

GPB_FINAL @interface API_CLIENTCapFlowPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** TODO[default = ONE_DAY]; */
@property(nonatomic, readwrite) enum OBJECT_QUOTECapFlowType type;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECapFlowData *capflow;
/** Test to see if @c capflow has been set. */
@property(nonatomic, readwrite) BOOL hasCapflow;

@end

/**
 * Fetches the raw value of a @c API_CLIENTCapFlowPush's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTCapFlowPush_Type_RawValue(API_CLIENTCapFlowPush *message);
/**
 * Sets the raw value of an @c API_CLIENTCapFlowPush's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTCapFlowPush_Type_RawValue(API_CLIENTCapFlowPush *message, int32_t value);

#pragma mark - API_CLIENTCapNetPush

typedef GPB_ENUM(API_CLIENTCapNetPush_FieldNumber) {
  API_CLIENTCapNetPush_FieldNumber_Id_p = 1,
  API_CLIENTCapNetPush_FieldNumber_PriceBase = 2,
  API_CLIENTCapNetPush_FieldNumber_Capnet = 3,
};

GPB_FINAL @interface API_CLIENTCapNetPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECapNetData *capnet;
/** Test to see if @c capnet has been set. */
@property(nonatomic, readwrite) BOOL hasCapnet;

@end

#pragma mark - API_CLIENTOrderBookPush

typedef GPB_ENUM(API_CLIENTOrderBookPush_FieldNumber) {
  API_CLIENTOrderBookPush_FieldNumber_Id_p = 1,
  API_CLIENTOrderBookPush_FieldNumber_PriceBase = 2,
  API_CLIENTOrderBookPush_FieldNumber_OrderBook = 3,
};

GPB_FINAL @interface API_CLIENTOrderBookPush : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEOrderBook *orderBook;
/** Test to see if @c orderBook has been set. */
@property(nonatomic, readwrite) BOOL hasOrderBook;

@end

#pragma mark - API_CLIENTRtSimpleQuote

typedef GPB_ENUM(API_CLIENTRtSimpleQuote_FieldNumber) {
  API_CLIENTRtSimpleQuote_FieldNumber_Id_p = 1,
  API_CLIENTRtSimpleQuote_FieldNumber_Seq = 2,
  API_CLIENTRtSimpleQuote_FieldNumber_PriceBase = 3,
  API_CLIENTRtSimpleQuote_FieldNumber_Time = 4,
  API_CLIENTRtSimpleQuote_FieldNumber_Price = 5,
  API_CLIENTRtSimpleQuote_FieldNumber_MsgSendTime = 6,
  API_CLIENTRtSimpleQuote_FieldNumber_AskPrice = 7,
  API_CLIENTRtSimpleQuote_FieldNumber_AskSize = 8,
  API_CLIENTRtSimpleQuote_FieldNumber_BidPrice = 9,
  API_CLIENTRtSimpleQuote_FieldNumber_BidSize = 10,
  API_CLIENTRtSimpleQuote_FieldNumber_QuoteType = 11,
};

GPB_FINAL @interface API_CLIENTRtSimpleQuote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 行情序号 */
@property(nonatomic, readwrite) uint32_t seq;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

/** 时间，表示格式YYYYMMDDHHMM(年月日时分) */
@property(nonatomic, readwrite) uint64_t time;

/** 分时价 */
@property(nonatomic, readwrite) int64_t price;

/** time for sending this quote into kafka */
@property(nonatomic, readwrite) int64_t msgSendTime;

@property(nonatomic, readwrite) int64_t askPrice;

@property(nonatomic, readwrite) int64_t askSize;

@property(nonatomic, readwrite) int64_t bidPrice;

@property(nonatomic, readwrite) int64_t bidSize;

@property(nonatomic, readwrite) enum OBJECT_QUOTEQuoteType quoteType;

@end

/**
 * Fetches the raw value of a @c API_CLIENTRtSimpleQuote's @c quoteType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t API_CLIENTRtSimpleQuote_QuoteType_RawValue(API_CLIENTRtSimpleQuote *message);
/**
 * Sets the raw value of an @c API_CLIENTRtSimpleQuote's @c quoteType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPI_CLIENTRtSimpleQuote_QuoteType_RawValue(API_CLIENTRtSimpleQuote *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
