// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object/quote/quote.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class OBJECT_QUOTEADRHQuote;
@class OBJECT_QUOTEAHQuote;
@class OBJECT_QUOTEBondQuoteData;
@class OBJECT_QUOTEBrokerData;
@class OBJECT_QUOTEBrokerDetail;
@class OBJECT_QUOTECASQuote;
@class OBJECT_QUOTEFundQuoteData;
@class OBJECT_QUOTEIndexQuoteData;
@class OBJECT_QUOTEMarketStatusInfo;
@class OBJECT_QUOTEOptionBriefData;
@class OBJECT_QUOTEOptionChainsDataRow;
@class OBJECT_QUOTEOptionQuoteData;
@class OBJECT_QUOTEOrder;
@class OBJECT_QUOTEPosition;
@class OBJECT_QUOTEPositionData;
@class OBJECT_QUOTEQuoteData;
@class OBJECT_QUOTESectorQuoteData;
@class OBJECT_QUOTESimpleQuote;
@class OBJECT_QUOTEStockQuoteData;
@class OBJECT_QUOTEUnderlyingQuote;
@class OBJECT_QUOTEVCMQuote;
@class OBJECT_QUOTEWarrantQuoteData;
@class OBJECT_SECUFullID;
@class OBJECT_SECUInfo;
@class OBJECT_SECUSecurityName;
GPB_ENUM_FWD_DECLARE(OBJECT_MARKETExchange);
GPB_ENUM_FWD_DECLARE(OBJECT_MARKETMarketId);
GPB_ENUM_FWD_DECLARE(OBJECT_MARKETMarketStatus);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum OBJECT_QUOTEIMBDirection

/** 港股收盘竞价不能匹配方向 */
typedef GPB_ENUM(OBJECT_QUOTEIMBDirection) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEIMBDirection_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  OBJECT_QUOTEIMBDirection_ImbNone = 0,
  OBJECT_QUOTEIMBDirection_ImbEqule = 1,
  OBJECT_QUOTEIMBDirection_ImbBuy = 2,
  OBJECT_QUOTEIMBDirection_ImbSell = 3,
};

GPBEnumDescriptor *OBJECT_QUOTEIMBDirection_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEIMBDirection_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTETradingStatus

/** 证券交易状态 */
typedef GPB_ENUM(OBJECT_QUOTETradingStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTETradingStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  OBJECT_QUOTETradingStatus_TsUnknown = 0,

  /** 停牌 */
  OBJECT_QUOTETradingStatus_TsSuspended = 1,

  /** 港股波动中断 */
  OBJECT_QUOTETradingStatus_TsVolatility = 2,

  /** 未上市 */
  OBJECT_QUOTETradingStatus_TsUnlisted = 3,

  /** 暂停上市 (A股) */
  OBJECT_QUOTETradingStatus_TsZanting = 4,

  /** 退市 */
  OBJECT_QUOTETradingStatus_TsDelisting = 5,

  /** 交易中 */
  OBJECT_QUOTETradingStatus_TsNormal = 6,

  /** 待上市 */
  OBJECT_QUOTETradingStatus_TsToBeListed = 7,

  /** 待开盘 */
  OBJECT_QUOTETradingStatus_TsToBeOpened = 8,
};

GPBEnumDescriptor *OBJECT_QUOTETradingStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTETradingStatus_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEQuoteType

/** 行情类别 */
typedef GPB_ENUM(OBJECT_QUOTEQuoteType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEQuoteType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未知 */
  OBJECT_QUOTEQuoteType_QtNone = 0,

  /** 债券 */
  OBJECT_QUOTEQuoteType_QtBond = 1,

  /** 正股 */
  OBJECT_QUOTEQuoteType_QtEqty = 2,

  /** 信托,基金,ETF */
  OBJECT_QUOTEQuoteType_QtTrst = 3,

  /** 涡轮，牛熊 */
  OBJECT_QUOTEQuoteType_QtWrnt = 4,

  /** 指数 */
  OBJECT_QUOTEQuoteType_QtIndex = 5,

  /** 期权 */
  OBJECT_QUOTEQuoteType_QtOption = 6,

  /** 板块 */
  OBJECT_QUOTEQuoteType_QtPlate = 7,

  /** 每日杠杆 */
  OBJECT_QUOTEQuoteType_QtDlc = 8,
};

GPBEnumDescriptor *OBJECT_QUOTEQuoteType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEQuoteType_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEPlateSetType

typedef GPB_ENUM(OBJECT_QUOTEPlateSetType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEPlateSetType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  OBJECT_QUOTEPlateSetType_PlateNone = 0,

  /** 所有板块 */
  OBJECT_QUOTEPlateSetType_PlateAll = 1,

  /** 行业板块 */
  OBJECT_QUOTEPlateSetType_PlateIndustry = 2,

  /** 地域板块,港美股市场的地域分类数据暂为空 */
  OBJECT_QUOTEPlateSetType_PlateRegion = 3,

  /** 概念板块 */
  OBJECT_QUOTEPlateSetType_PlateConcept = 4,
};

GPBEnumDescriptor *OBJECT_QUOTEPlateSetType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEPlateSetType_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEWarrantType

typedef GPB_ENUM(OBJECT_QUOTEWarrantType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEWarrantType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未知 */
  OBJECT_QUOTEWarrantType_WrntNone = 0,

  /** 认购 */
  OBJECT_QUOTEWarrantType_WrntBuy = 1,

  /** 认沽 */
  OBJECT_QUOTEWarrantType_WrntSell = 2,

  /** 牛 */
  OBJECT_QUOTEWarrantType_WrntBull = 3,

  /** 熊 */
  OBJECT_QUOTEWarrantType_WrntBear = 4,
};

GPBEnumDescriptor *OBJECT_QUOTEWarrantType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEWarrantType_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEQuoteScene

/** 实时行情使用场景 */
typedef GPB_ENUM(OBJECT_QUOTEQuoteScene) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEQuoteScene_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 全量股票信息，全量行情 */
  OBJECT_QUOTEQuoteScene_QsFull = 0,

  /** 移动端列表, 股票信息包含基础静态信息，行情包含现价、涨跌、涨跌价 */
  OBJECT_QUOTEQuoteScene_QsMobileBrief1 = 1,

  /** 客户端列表，股票信息包含基础静态信息，全量行情 */
  OBJECT_QUOTEQuoteScene_QsDesktopBrief1 = 2,

  /** 自定义方式 */
  OBJECT_QUOTEQuoteScene_QsCustom = 127,
};

GPBEnumDescriptor *OBJECT_QUOTEQuoteScene_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEQuoteScene_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEMoneynessType

typedef GPB_ENUM(OBJECT_QUOTEMoneynessType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEMoneynessType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 全部 */
  OBJECT_QUOTEMoneynessType_MtAll = 0,

  /** 价内 */
  OBJECT_QUOTEMoneynessType_MtIn = 1,

  /** 价外 */
  OBJECT_QUOTEMoneynessType_MtOut = 2,

  /** 其他类型 */
  OBJECT_QUOTEMoneynessType_MtOther = 3,
};

GPBEnumDescriptor *OBJECT_QUOTEMoneynessType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEMoneynessType_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEStockConnectMarket

typedef GPB_ENUM(OBJECT_QUOTEStockConnectMarket) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEStockConnectMarket_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  OBJECT_QUOTEStockConnectMarket_ScmUnknown = 0,

  /** 沪股通 */
  OBJECT_QUOTEStockConnectMarket_ScmHk2Sh = 1,

  /** 深股通 */
  OBJECT_QUOTEStockConnectMarket_ScmHk2Sz = 2,

  /** 港股通（沪） */
  OBJECT_QUOTEStockConnectMarket_ScmSh2Hk = 3,

  /** 港股通（深） */
  OBJECT_QUOTEStockConnectMarket_ScmSz2Hk = 4,
};

GPBEnumDescriptor *OBJECT_QUOTEStockConnectMarket_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEStockConnectMarket_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEUsTime

typedef GPB_ENUM(OBJECT_QUOTEUsTime) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEUsTime_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  OBJECT_QUOTEUsTime_UsUnknownTime = 0,

  /** 夏令时 */
  OBJECT_QUOTEUsTime_UsSummerTime = 1,

  /** 冬令时 */
  OBJECT_QUOTEUsTime_UsWinterTime = 2,
};

GPBEnumDescriptor *OBJECT_QUOTEUsTime_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEUsTime_IsValidValue(int32_t value);

#pragma mark - OBJECT_QUOTEQuoteRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OBJECT_QUOTEQuoteRoot : GPBRootObject
@end

#pragma mark - OBJECT_QUOTEMarketStatusInfo

typedef GPB_ENUM(OBJECT_QUOTEMarketStatusInfo_FieldNumber) {
  OBJECT_QUOTEMarketStatusInfo_FieldNumber_MktTime = 1,
  OBJECT_QUOTEMarketStatusInfo_FieldNumber_Market = 2,
  OBJECT_QUOTEMarketStatusInfo_FieldNumber_Status = 3,
  OBJECT_QUOTEMarketStatusInfo_FieldNumber_Desc = 4,
  OBJECT_QUOTEMarketStatusInfo_FieldNumber_StatusDescArray = 5,
};

GPB_FINAL @interface OBJECT_QUOTEMarketStatusInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t mktTime;

@property(nonatomic, readwrite) enum OBJECT_MARKETMarketId market;

@property(nonatomic, readwrite) enum OBJECT_MARKETMarketStatus status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_SECUSecurityName*> *statusDescArray;
/** The number of items in @c statusDescArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger statusDescArray_Count;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEMarketStatusInfo's @c market property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEMarketStatusInfo_Market_RawValue(OBJECT_QUOTEMarketStatusInfo *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEMarketStatusInfo's @c market property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEMarketStatusInfo_Market_RawValue(OBJECT_QUOTEMarketStatusInfo *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTEMarketStatusInfo's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEMarketStatusInfo_Status_RawValue(OBJECT_QUOTEMarketStatusInfo *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEMarketStatusInfo's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEMarketStatusInfo_Status_RawValue(OBJECT_QUOTEMarketStatusInfo *message, int32_t value);

#pragma mark - OBJECT_QUOTEStockConnectInfo

typedef GPB_ENUM(OBJECT_QUOTEStockConnectInfo_FieldNumber) {
  OBJECT_QUOTEStockConnectInfo_FieldNumber_Scm = 1,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_LatestTime = 2,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_DqbTime = 3,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_Dqb = 4,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_Buy = 5,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_Sell = 6,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_BuySell = 7,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_DqbTotal = 8,
  OBJECT_QUOTEStockConnectInfo_FieldNumber_Rate = 9,
};

GPB_FINAL @interface OBJECT_QUOTEStockConnectInfo : GPBMessage

@property(nonatomic, readwrite) OBJECT_QUOTEStockConnectMarket scm;

/** 市场行情时间 YYYYMMDDHHMMSSsss */
@property(nonatomic, readwrite) uint64_t latestTime;

/** 剩余额度行情时间 YYYYMMDDHHMMSSsss */
@property(nonatomic, readwrite) uint64_t dqbTime;

/** 剩余额度 */
@property(nonatomic, readwrite) int64_t dqb;

/** 买入 */
@property(nonatomic, readwrite) int64_t buy;

/** 卖出 */
@property(nonatomic, readwrite) int64_t sell;

/** 买入卖出 */
@property(nonatomic, readwrite) int64_t buySell;

/** 总额度 */
@property(nonatomic, readwrite) int64_t dqbTotal;

/** 剩余额度比率 */
@property(nonatomic, readwrite) int32_t rate;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEStockConnectInfo's @c scm property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEStockConnectInfo_Scm_RawValue(OBJECT_QUOTEStockConnectInfo *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEStockConnectInfo's @c scm property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEStockConnectInfo_Scm_RawValue(OBJECT_QUOTEStockConnectInfo *message, int32_t value);

#pragma mark - OBJECT_QUOTEBrokerDetail

typedef GPB_ENUM(OBJECT_QUOTEBrokerDetail_FieldNumber) {
  OBJECT_QUOTEBrokerDetail_FieldNumber_Id_p = 1,
  OBJECT_QUOTEBrokerDetail_FieldNumber_Name = 2,
};

GPB_FINAL @interface OBJECT_QUOTEBrokerDetail : GPBMessage

/** 买盘经纪ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 买盘经纪名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - OBJECT_QUOTEBrokerData

typedef GPB_ENUM(OBJECT_QUOTEBrokerData_FieldNumber) {
  OBJECT_QUOTEBrokerData_FieldNumber_BidBrokerArray = 1,
  OBJECT_QUOTEBrokerData_FieldNumber_AskBrokerArray = 2,
  OBJECT_QUOTEBrokerData_FieldNumber_LatestTime = 3,
};

GPB_FINAL @interface OBJECT_QUOTEBrokerData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEBrokerDetail*> *bidBrokerArray;
/** The number of items in @c bidBrokerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidBrokerArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEBrokerDetail*> *askBrokerArray;
/** The number of items in @c askBrokerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askBrokerArray_Count;

/** 冗余字段 */
@property(nonatomic, readwrite) uint64_t latestTime;

@end

#pragma mark - OBJECT_QUOTEOptionBriefData

typedef GPB_ENUM(OBJECT_QUOTEOptionBriefData_FieldNumber) {
  OBJECT_QUOTEOptionBriefData_FieldNumber_Market = 1,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Code = 2,
  OBJECT_QUOTEOptionBriefData_FieldNumber_LatestTime = 3,
  OBJECT_QUOTEOptionBriefData_FieldNumber_LatestPrice = 4,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Volume = 5,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Amount = 6,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Netchng = 7,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Pctchng = 8,
  OBJECT_QUOTEOptionBriefData_FieldNumber_AskVolume = 9,
  OBJECT_QUOTEOptionBriefData_FieldNumber_AskPrice = 10,
  OBJECT_QUOTEOptionBriefData_FieldNumber_BidVolume = 11,
  OBJECT_QUOTEOptionBriefData_FieldNumber_BidPrice = 12,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Premium = 13,
  OBJECT_QUOTEOptionBriefData_FieldNumber_ImpliedVolatility = 14,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Delta = 15,
  OBJECT_QUOTEOptionBriefData_FieldNumber_OpenInt = 16,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Gamma = 17,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Theta = 18,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Vega = 19,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Rho = 20,
  OBJECT_QUOTEOptionBriefData_FieldNumber_BreakevenPoint = 21,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Multiplier = 22,
  OBJECT_QUOTEOptionBriefData_FieldNumber_ContractSize = 23,
  OBJECT_QUOTEOptionBriefData_FieldNumber_StrikePrice = 30,
  OBJECT_QUOTEOptionBriefData_FieldNumber_MaturityDate = 31,
  OBJECT_QUOTEOptionBriefData_FieldNumber_PriceBase = 32,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Name = 33,
  OBJECT_QUOTEOptionBriefData_FieldNumber_Caflag = 34,
};

/**
 * 单一期权类型
 **/
GPB_FINAL @interface OBJECT_QUOTEOptionBriefData : GPBMessage

/** 市场 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *market;

/** 代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

/** 最新时间 */
@property(nonatomic, readwrite) uint64_t latestTime;

@property(nonatomic, readwrite) uint64_t latestPrice;

@property(nonatomic, readwrite) uint64_t volume;

@property(nonatomic, readwrite) uint64_t amount;

/** 涨跌额 */
@property(nonatomic, readwrite) int64_t netchng;

/** 涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

@property(nonatomic, readwrite) uint64_t askVolume;

@property(nonatomic, readwrite) uint64_t askPrice;

@property(nonatomic, readwrite) uint64_t bidVolume;

@property(nonatomic, readwrite) uint64_t bidPrice;

/** 溢价,使用时除以 100 */
@property(nonatomic, readwrite) int32_t premium;

/** 引申波幅 */
@property(nonatomic, readwrite) int32_t impliedVolatility;

/** 对冲值 */
@property(nonatomic, readwrite) int32_t delta;

/** 未平仓数 */
@property(nonatomic, readwrite) uint64_t openInt;

/** Gamma(Delta变化/标的资产价格变化；期权价格对标的资产价格的二阶导数) */
@property(nonatomic, readwrite) int32_t gamma;

/** Theta(期权价格变化/期权有效期变化；期权价格对时间的一阶导数) */
@property(nonatomic, readwrite) int32_t theta;

/** Vega(期权价格变化/标的资产价格波动率的变化；期权价格对波动率的一阶导数) */
@property(nonatomic, readwrite) int32_t vega;

/** Rho（期权价格变化/利率变化；期权价格对无风险利率的一阶导数） */
@property(nonatomic, readwrite) int32_t rho;

/** 打和点 */
@property(nonatomic, readwrite) int64_t breakevenPoint;

/** 合约乘数 */
@property(nonatomic, readwrite) uint32_t multiplier;

/** 合约规模 */
@property(nonatomic, readwrite) uint32_t contractSize;

/** 行权价 */
@property(nonatomic, readwrite) uint64_t strikePrice;

/** 到期日 */
@property(nonatomic, readwrite) uint64_t maturityDate;

/** 价格基数 */
@property(nonatomic, readwrite) uint64_t priceBase;

/** 名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 是否标记CA */
@property(nonatomic, readwrite) BOOL caflag;

@end

#pragma mark - OBJECT_QUOTEOptionMaturityDate

typedef GPB_ENUM(OBJECT_QUOTEOptionMaturityDate_FieldNumber) {
  OBJECT_QUOTEOptionMaturityDate_FieldNumber_MaturityDate = 1,
  OBJECT_QUOTEOptionMaturityDate_FieldNumber_RemainingTime = 2,
};

/**
 * 期权T型报价
 **/
GPB_FINAL @interface OBJECT_QUOTEOptionMaturityDate : GPBMessage

/** 日期 */
@property(nonatomic, readwrite) uint64_t maturityDate;

/** 剩余时间，单位为：天 */
@property(nonatomic, readwrite) uint32_t remainingTime;

@end

#pragma mark - OBJECT_QUOTEOptionChainsData

typedef GPB_ENUM(OBJECT_QUOTEOptionChainsData_FieldNumber) {
  OBJECT_QUOTEOptionChainsData_FieldNumber_CallGroupArray = 1,
  OBJECT_QUOTEOptionChainsData_FieldNumber_PutGroupArray = 2,
  OBJECT_QUOTEOptionChainsData_FieldNumber_CallNumber = 3,
  OBJECT_QUOTEOptionChainsData_FieldNumber_PutNumber = 4,
};

/**
 * 期权T型报价
 **/
GPB_FINAL @interface OBJECT_QUOTEOptionChainsData : GPBMessage

/** call 类型 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEOptionBriefData*> *callGroupArray;
/** The number of items in @c callGroupArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger callGroupArray_Count;

/** put 类型 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEOptionBriefData*> *putGroupArray;
/** The number of items in @c putGroupArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger putGroupArray_Count;

@property(nonatomic, readwrite) uint32_t callNumber;

@property(nonatomic, readwrite) uint32_t putNumber;

@end

#pragma mark - OBJECT_QUOTEOptionChainsDataRow

typedef GPB_ENUM(OBJECT_QUOTEOptionChainsDataRow_FieldNumber) {
  OBJECT_QUOTEOptionChainsDataRow_FieldNumber_CallData = 1,
  OBJECT_QUOTEOptionChainsDataRow_FieldNumber_PutData = 2,
  OBJECT_QUOTEOptionChainsDataRow_FieldNumber_StrikePrice = 3,
};

GPB_FINAL @interface OBJECT_QUOTEOptionChainsDataRow : GPBMessage

/** call 类型 */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEOptionBriefData *callData;
/** Test to see if @c callData has been set. */
@property(nonatomic, readwrite) BOOL hasCallData;

/** put 类型 */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEOptionBriefData *putData;
/** Test to see if @c putData has been set. */
@property(nonatomic, readwrite) BOOL hasPutData;

/** 行权价 实际值 =  除10^pricebase */
@property(nonatomic, readwrite) int64_t strikePrice;

@end

#pragma mark - OBJECT_QUOTEOptionChainsDataRowList

typedef GPB_ENUM(OBJECT_QUOTEOptionChainsDataRowList_FieldNumber) {
  OBJECT_QUOTEOptionChainsDataRowList_FieldNumber_RowListArray = 1,
  OBJECT_QUOTEOptionChainsDataRowList_FieldNumber_CallNumber = 2,
  OBJECT_QUOTEOptionChainsDataRowList_FieldNumber_PutNumber = 3,
  OBJECT_QUOTEOptionChainsDataRowList_FieldNumber_PriceBase = 4,
};

GPB_FINAL @interface OBJECT_QUOTEOptionChainsDataRowList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEOptionChainsDataRow*> *rowListArray;
/** The number of items in @c rowListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rowListArray_Count;

@property(nonatomic, readwrite) uint32_t callNumber;

@property(nonatomic, readwrite) uint32_t putNumber;

/** 价格基数 */
@property(nonatomic, readwrite) uint64_t priceBase;

@end

#pragma mark - OBJECT_QUOTEPositionData

typedef GPB_ENUM(OBJECT_QUOTEPositionData_FieldNumber) {
  OBJECT_QUOTEPositionData_FieldNumber_BidPrice = 1,
  OBJECT_QUOTEPositionData_FieldNumber_BidSize = 2,
  OBJECT_QUOTEPositionData_FieldNumber_BidOrderCount = 3,
  OBJECT_QUOTEPositionData_FieldNumber_AskPrice = 4,
  OBJECT_QUOTEPositionData_FieldNumber_AskSize = 5,
  OBJECT_QUOTEPositionData_FieldNumber_AskOrderCount = 6,
  OBJECT_QUOTEPositionData_FieldNumber_BidExchange = 7,
  OBJECT_QUOTEPositionData_FieldNumber_AskExchange = 8,
};

GPB_FINAL @interface OBJECT_QUOTEPositionData : GPBMessage

/** 委买价 */
@property(nonatomic, readwrite) int64_t bidPrice;

/** 委买量 */
@property(nonatomic, readwrite) uint64_t bidSize;

/** 买委托订单个数() */
@property(nonatomic, readwrite) uint64_t bidOrderCount;

/** 委卖价 */
@property(nonatomic, readwrite) int64_t askPrice;

/** 委卖量 */
@property(nonatomic, readwrite) uint64_t askSize;

/** 卖委托订单个数() */
@property(nonatomic, readwrite) uint64_t askOrderCount;

@property(nonatomic, readwrite) enum OBJECT_MARKETExchange bidExchange;

@property(nonatomic, readwrite) enum OBJECT_MARKETExchange askExchange;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEPositionData's @c bidExchange property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEPositionData_BidExchange_RawValue(OBJECT_QUOTEPositionData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEPositionData's @c bidExchange property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEPositionData_BidExchange_RawValue(OBJECT_QUOTEPositionData *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTEPositionData's @c askExchange property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEPositionData_AskExchange_RawValue(OBJECT_QUOTEPositionData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEPositionData's @c askExchange property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEPositionData_AskExchange_RawValue(OBJECT_QUOTEPositionData *message, int32_t value);

#pragma mark - OBJECT_QUOTEVCMQuote

typedef GPB_ENUM(OBJECT_QUOTEVCMQuote_FieldNumber) {
  OBJECT_QUOTEVCMQuote_FieldNumber_StartTime = 1,
  OBJECT_QUOTEVCMQuote_FieldNumber_EndTime = 2,
  OBJECT_QUOTEVCMQuote_FieldNumber_RefPrice = 3,
  OBJECT_QUOTEVCMQuote_FieldNumber_LowerPrice = 4,
  OBJECT_QUOTEVCMQuote_FieldNumber_UpperPrice = 5,
};

/**
 * 市调机制
 **/
GPB_FINAL @interface OBJECT_QUOTEVCMQuote : GPBMessage

/** 开始时间 */
@property(nonatomic, readwrite) uint64_t startTime;

/** 结束时间 */
@property(nonatomic, readwrite) uint64_t endTime;

/** 参考价格 */
@property(nonatomic, readwrite) int64_t refPrice;

/** 价格下限 */
@property(nonatomic, readwrite) int64_t lowerPrice;

/** 价格上限 */
@property(nonatomic, readwrite) int64_t upperPrice;

@end

#pragma mark - OBJECT_QUOTECASQuote

typedef GPB_ENUM(OBJECT_QUOTECASQuote_FieldNumber) {
  OBJECT_QUOTECASQuote_FieldNumber_RefPrice = 1,
  OBJECT_QUOTECASQuote_FieldNumber_LowerPrice = 2,
  OBJECT_QUOTECASQuote_FieldNumber_UpperPrice = 3,
  OBJECT_QUOTECASQuote_FieldNumber_ImbDirection = 4,
  OBJECT_QUOTECASQuote_FieldNumber_OrdImbQty = 5,
  OBJECT_QUOTECASQuote_FieldNumber_IePrice = 6,
  OBJECT_QUOTECASQuote_FieldNumber_IeVol = 7,
};

/**
 * 收盘集合竞价
 **/
GPB_FINAL @interface OBJECT_QUOTECASQuote : GPBMessage

/** 参考价格 */
@property(nonatomic, readwrite) int64_t refPrice;

/** 价格下限 */
@property(nonatomic, readwrite) int64_t lowerPrice;

/** 价格上限 */
@property(nonatomic, readwrite) int64_t upperPrice;

/** 不能配对方向 */
@property(nonatomic, readwrite) OBJECT_QUOTEIMBDirection imbDirection;

/** 不能配对数量 */
@property(nonatomic, readwrite) uint64_t ordImbQty;

@property(nonatomic, readwrite) int64_t iePrice;

@property(nonatomic, readwrite) int64_t ieVol;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTECASQuote's @c imbDirection property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTECASQuote_ImbDirection_RawValue(OBJECT_QUOTECASQuote *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTECASQuote's @c imbDirection property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTECASQuote_ImbDirection_RawValue(OBJECT_QUOTECASQuote *message, int32_t value);

#pragma mark - OBJECT_QUOTEAHQuote

typedef GPB_ENUM(OBJECT_QUOTEAHQuote_FieldNumber) {
  OBJECT_QUOTEAHQuote_FieldNumber_Id_p = 1,
  OBJECT_QUOTEAHQuote_FieldNumber_LatestPrice = 2,
  OBJECT_QUOTEAHQuote_FieldNumber_Netchng = 3,
  OBJECT_QUOTEAHQuote_FieldNumber_Pctchng = 4,
  OBJECT_QUOTEAHQuote_FieldNumber_Premium = 5,
  OBJECT_QUOTEAHQuote_FieldNumber_PriceBase = 6,
  OBJECT_QUOTEAHQuote_FieldNumber_LatestTime = 7,
};

GPB_FINAL @interface OBJECT_QUOTEAHQuote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 最新价 */
@property(nonatomic, readwrite) int64_t latestPrice;

/** 涨跌额 */
@property(nonatomic, readwrite) int64_t netchng;

/** 涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

/** AH股溢价,使用时除以 100 */
@property(nonatomic, readwrite) int32_t premium;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

/** 时间 */
@property(nonatomic, readwrite) uint64_t latestTime;

@end

#pragma mark - OBJECT_QUOTERelateQuote

typedef GPB_ENUM(OBJECT_QUOTERelateQuote_FieldNumber) {
  OBJECT_QUOTERelateQuote_FieldNumber_Id_p = 1,
  OBJECT_QUOTERelateQuote_FieldNumber_LatestTime = 2,
  OBJECT_QUOTERelateQuote_FieldNumber_LatestPrice = 3,
  OBJECT_QUOTERelateQuote_FieldNumber_Netchng = 4,
  OBJECT_QUOTERelateQuote_FieldNumber_Pctchng = 5,
  OBJECT_QUOTERelateQuote_FieldNumber_PriceBase = 6,
};

GPB_FINAL @interface OBJECT_QUOTERelateQuote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 对应代码的最新行情时间 */
@property(nonatomic, readwrite) uint64_t latestTime;

/** 对应代码最新价 */
@property(nonatomic, readwrite) int64_t latestPrice;

/** 对应代码涨跌额 */
@property(nonatomic, readwrite) int64_t netchng;

/** 对应代码涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@end

#pragma mark - OBJECT_QUOTEADRHQuote

typedef GPB_ENUM(OBJECT_QUOTEADRHQuote_FieldNumber) {
  OBJECT_QUOTEADRHQuote_FieldNumber_Id_p = 1,
  OBJECT_QUOTEADRHQuote_FieldNumber_ConvPrice = 2,
  OBJECT_QUOTEADRHQuote_FieldNumber_ConvRatio = 3,
  OBJECT_QUOTEADRHQuote_FieldNumber_RelaNetchng = 4,
  OBJECT_QUOTEADRHQuote_FieldNumber_RelaPctchng = 5,
  OBJECT_QUOTEADRHQuote_FieldNumber_LatestPrice = 6,
  OBJECT_QUOTEADRHQuote_FieldNumber_Netchng = 7,
  OBJECT_QUOTEADRHQuote_FieldNumber_Pctchng = 8,
  OBJECT_QUOTEADRHQuote_FieldNumber_LatestTime = 9,
  OBJECT_QUOTEADRHQuote_FieldNumber_PriceBase = 10,
};

GPB_FINAL @interface OBJECT_QUOTEADRHQuote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** ADR换算价（HKD） = ADR报价（USD）/换股比率*汇率,汇率：1USD = 7.838HKD */
@property(nonatomic, readwrite) int64_t convPrice;

/** ADR换股比率 */
@property(nonatomic, readwrite) uint32_t convRatio;

/** 对应代码涨跌额（ADR相对港股） */
@property(nonatomic, readwrite) int64_t relaNetchng;

/** 相对代码涨跌幅, 使用时除以 100(ADR相对港股) */
@property(nonatomic, readwrite) int32_t relaPctchng;

/** 对应代码最新价 */
@property(nonatomic, readwrite) int64_t latestPrice;

/** 对应代码涨跌额 */
@property(nonatomic, readwrite) int64_t netchng;

/** 对应代码涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

/** 对应代码的最新行情时间 */
@property(nonatomic, readwrite) uint64_t latestTime;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@end

#pragma mark - OBJECT_QUOTEUnderlyingQuote

typedef GPB_ENUM(OBJECT_QUOTEUnderlyingQuote_FieldNumber) {
  OBJECT_QUOTEUnderlyingQuote_FieldNumber_Id_p = 1,
  OBJECT_QUOTEUnderlyingQuote_FieldNumber_LatestPrice = 2,
  OBJECT_QUOTEUnderlyingQuote_FieldNumber_Netchng = 3,
  OBJECT_QUOTEUnderlyingQuote_FieldNumber_Pctchng = 4,
  OBJECT_QUOTEUnderlyingQuote_FieldNumber_PriceBase = 5,
};

GPB_FINAL @interface OBJECT_QUOTEUnderlyingQuote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 最新价 */
@property(nonatomic, readwrite) int64_t latestPrice;

/** 涨跌额 */
@property(nonatomic, readwrite) int64_t netchng;

/** 涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

@end

#pragma mark - OBJECT_QUOTEPosition

typedef GPB_ENUM(OBJECT_QUOTEPosition_FieldNumber) {
  OBJECT_QUOTEPosition_FieldNumber_LatestTime = 1,
  OBJECT_QUOTEPosition_FieldNumber_CittDiff = 2,
  OBJECT_QUOTEPosition_FieldNumber_CittThan = 3,
  OBJECT_QUOTEPosition_FieldNumber_TotalBidSize = 4,
  OBJECT_QUOTEPosition_FieldNumber_TotalAskSize = 5,
  OBJECT_QUOTEPosition_FieldNumber_PosDataArray = 6,
};

GPB_FINAL @interface OBJECT_QUOTEPosition : GPBMessage

/** 市场行情时间 YYYYMMDDHHMMSSsss */
@property(nonatomic, readwrite) uint64_t latestTime;

/** 委差 */
@property(nonatomic, readwrite) int64_t cittDiff;

/** 委比, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t cittThan;

/** 买总 */
@property(nonatomic, readwrite) int64_t totalBidSize;

/** 卖总 */
@property(nonatomic, readwrite) int64_t totalAskSize;

/** 买卖档细节 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEPositionData*> *posDataArray;
/** The number of items in @c posDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger posDataArray_Count;

@end

#pragma mark - OBJECT_QUOTEQuote

typedef GPB_ENUM(OBJECT_QUOTEQuote_FieldNumber) {
  OBJECT_QUOTEQuote_FieldNumber_Id_p = 1,
  OBJECT_QUOTEQuote_FieldNumber_PriceBase = 2,
  OBJECT_QUOTEQuote_FieldNumber_MsInfo = 3,
  OBJECT_QUOTEQuote_FieldNumber_Info = 4,
  OBJECT_QUOTEQuote_FieldNumber_QuoteData = 5,
  OBJECT_QUOTEQuote_FieldNumber_SQuote = 6,
  OBJECT_QUOTEQuote_FieldNumber_Pos = 7,
  OBJECT_QUOTEQuote_FieldNumber_BrokerData = 8,
  OBJECT_QUOTEQuote_FieldNumber_RecvTime = 19,
  OBJECT_QUOTEQuote_FieldNumber_Delay = 20,
};

GPB_FINAL @interface OBJECT_QUOTEQuote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 价格小数计算基数，10的幂次表示 */
@property(nonatomic, readwrite) uint32_t priceBase;

/** 市场状态 */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEMarketStatusInfo *msInfo;
/** Test to see if @c msInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMsInfo;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEQuoteData *quoteData;
/** Test to see if @c quoteData has been set. */
@property(nonatomic, readwrite) BOOL hasQuoteData;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTESimpleQuote *sQuote;
/** Test to see if @c sQuote has been set. */
@property(nonatomic, readwrite) BOOL hasSQuote;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEPosition *pos;
/** Test to see if @c pos has been set. */
@property(nonatomic, readwrite) BOOL hasPos;

/** 经纪席位 */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEBrokerData *brokerData;
/** Test to see if @c brokerData has been set. */
@property(nonatomic, readwrite) BOOL hasBrokerData;

@property(nonatomic, readwrite) uint64_t recvTime;

/** 延时行情标志,true为延时行情 */
@property(nonatomic, readwrite) BOOL delay;

@end

#pragma mark - OBJECT_QUOTEQuoteData

typedef GPB_ENUM(OBJECT_QUOTEQuoteData_FieldNumber) {
  OBJECT_QUOTEQuoteData_FieldNumber_Seq = 1,
  OBJECT_QUOTEQuoteData_FieldNumber_LatestTime = 2,
  OBJECT_QUOTEQuoteData_FieldNumber_QtType = 3,
  OBJECT_QUOTEQuoteData_FieldNumber_PreClose = 4,
  OBJECT_QUOTEQuoteData_FieldNumber_Open = 5,
  OBJECT_QUOTEQuoteData_FieldNumber_LatestPrice = 6,
  OBJECT_QUOTEQuoteData_FieldNumber_High = 7,
  OBJECT_QUOTEQuoteData_FieldNumber_Low = 8,
  OBJECT_QUOTEQuoteData_FieldNumber_Close = 9,
  OBJECT_QUOTEQuoteData_FieldNumber_Volume = 10,
  OBJECT_QUOTEQuoteData_FieldNumber_Amount = 11,
  OBJECT_QUOTEQuoteData_FieldNumber_Netchng = 12,
  OBJECT_QUOTEQuoteData_FieldNumber_Pctchng = 13,
  OBJECT_QUOTEQuoteData_FieldNumber_Amp = 14,
  OBJECT_QUOTEQuoteData_FieldNumber_Avg = 15,
  OBJECT_QUOTEQuoteData_FieldNumber_Week52High = 16,
  OBJECT_QUOTEQuoteData_FieldNumber_Week52Low = 17,
  OBJECT_QUOTEQuoteData_FieldNumber_HistoryHigh = 18,
  OBJECT_QUOTEQuoteData_FieldNumber_HistoryLow = 19,
  OBJECT_QUOTEQuoteData_FieldNumber_UpperLimit = 20,
  OBJECT_QUOTEQuoteData_FieldNumber_LowerLimit = 21,
  OBJECT_QUOTEQuoteData_FieldNumber_VolumeRatio = 22,
  OBJECT_QUOTEQuoteData_FieldNumber_TurnoverRate = 23,
  OBJECT_QUOTEQuoteData_FieldNumber_QtyUnit = 24,
  OBJECT_QUOTEQuoteData_FieldNumber_PostVolume = 25,
  OBJECT_QUOTEQuoteData_FieldNumber_PostAmount = 26,
  OBJECT_QUOTEQuoteData_FieldNumber_AskPrice = 30,
  OBJECT_QUOTEQuoteData_FieldNumber_AskSize = 31,
  OBJECT_QUOTEQuoteData_FieldNumber_BidPrice = 32,
  OBJECT_QUOTEQuoteData_FieldNumber_BidSize = 33,
  OBJECT_QUOTEQuoteData_FieldNumber_TrdStatus = 34,
  OBJECT_QUOTEQuoteData_FieldNumber_Accer = 36,
  OBJECT_QUOTEQuoteData_FieldNumber_Index = 40,
  OBJECT_QUOTEQuoteData_FieldNumber_Stock = 41,
  OBJECT_QUOTEQuoteData_FieldNumber_Fund = 42,
  OBJECT_QUOTEQuoteData_FieldNumber_Bond = 43,
  OBJECT_QUOTEQuoteData_FieldNumber_Warrant = 44,
  OBJECT_QUOTEQuoteData_FieldNumber_Option = 45,
  OBJECT_QUOTEQuoteData_FieldNumber_Sector = 46,
  OBJECT_QUOTEQuoteData_FieldNumber_UsTime = 50,
  OBJECT_QUOTEQuoteData_FieldNumber_PriceFlag = 51,
  OBJECT_QUOTEQuoteData_FieldNumber_PctChngThisYear = 52,
  OBJECT_QUOTEQuoteData_FieldNumber_PctChng5Day = 53,
  OBJECT_QUOTEQuoteData_FieldNumber_NetChngThisYear = 54,
  OBJECT_QUOTEQuoteData_FieldNumber_NetChng5Day = 55,
};

GPB_FINAL @interface OBJECT_QUOTEQuoteData : GPBMessage

/** 行情序号 */
@property(nonatomic, readwrite) uint32_t seq;

/** 市场行情时间 YYYYMMDDHHMMSSsss */
@property(nonatomic, readwrite) uint64_t latestTime;

/** 行情类别，决定读取后面哪个数据字段 */
@property(nonatomic, readwrite) OBJECT_QUOTEQuoteType qtType;

/** 昨收价 */
@property(nonatomic, readwrite) int64_t preClose;

/** 开盘价 */
@property(nonatomic, readwrite) int64_t open;

/** 最新价 */
@property(nonatomic, readwrite) int64_t latestPrice;

/** 最高价 */
@property(nonatomic, readwrite) int64_t high;

/** 最低价 */
@property(nonatomic, readwrite) int64_t low;

/** 收盘价 */
@property(nonatomic, readwrite) int64_t close;

/** 总成交量 */
@property(nonatomic, readwrite) uint64_t volume;

/** 总成交金额 */
@property(nonatomic, readwrite) int64_t amount;

/** 涨跌额 */
@property(nonatomic, readwrite) int64_t netchng;

/** 涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

/** 振幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t amp;

/** 均价 */
@property(nonatomic, readwrite) int64_t avg;

/** 52周最高 */
@property(nonatomic, readwrite) int64_t week52High;

/** 52周最低 */
@property(nonatomic, readwrite) int64_t week52Low;

/** 历史最高 */
@property(nonatomic, readwrite) int64_t historyHigh;

/** 历史最低 */
@property(nonatomic, readwrite) int64_t historyLow;

/** 涨停 */
@property(nonatomic, readwrite) int64_t upperLimit;

/** 跌停 */
@property(nonatomic, readwrite) int64_t lowerLimit;

/** 量比, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t volumeRatio;

/** 换手率 */
@property(nonatomic, readwrite) int32_t turnoverRate;

/** 实时价差 */
@property(nonatomic, readwrite) int32_t qtyUnit;

/** 盘后量,科创板使用 */
@property(nonatomic, readwrite) uint64_t postVolume;

/** 盘后额，科创板使用 */
@property(nonatomic, readwrite) int64_t postAmount;

/** 卖一价 */
@property(nonatomic, readwrite) int64_t askPrice;

/** 卖一量 */
@property(nonatomic, readwrite) uint64_t askSize;

/** 买一价 */
@property(nonatomic, readwrite) int64_t bidPrice;

/** 买一量 */
@property(nonatomic, readwrite) uint64_t bidSize;

/** 个股交易状态 */
@property(nonatomic, readwrite) OBJECT_QUOTETradingStatus trdStatus;

/** 5分钟涨速 */
@property(nonatomic, readwrite) int32_t accer;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEIndexQuoteData *index;
/** Test to see if @c index has been set. */
@property(nonatomic, readwrite) BOOL hasIndex;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEStockQuoteData *stock;
/** Test to see if @c stock has been set. */
@property(nonatomic, readwrite) BOOL hasStock;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEFundQuoteData *fund;
/** Test to see if @c fund has been set. */
@property(nonatomic, readwrite) BOOL hasFund;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEBondQuoteData *bond;
/** Test to see if @c bond has been set. */
@property(nonatomic, readwrite) BOOL hasBond;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEWarrantQuoteData *warrant;
/** Test to see if @c warrant has been set. */
@property(nonatomic, readwrite) BOOL hasWarrant;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEOptionQuoteData *option;
/** Test to see if @c option has been set. */
@property(nonatomic, readwrite) BOOL hasOption;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTESectorQuoteData *sector;
/** Test to see if @c sector has been set. */
@property(nonatomic, readwrite) BOOL hasSector;

/** 美股专用 */
@property(nonatomic, readwrite) OBJECT_QUOTEUsTime usTime;

/** 标记最新价是否是昨收补的 */
@property(nonatomic, readwrite) int32_t priceFlag;

/** 近一年涨跌幅 */
@property(nonatomic, readwrite) int32_t pctChngThisYear;

/** 近5日涨跌幅 */
@property(nonatomic, readwrite) int32_t pctChng5Day;

/** 近一年涨跌额 */
@property(nonatomic, readwrite) int64_t netChngThisYear;

/** 近5日涨跌额 */
@property(nonatomic, readwrite) int64_t netChng5Day;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEQuoteData's @c qtType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEQuoteData_QtType_RawValue(OBJECT_QUOTEQuoteData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEQuoteData's @c qtType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEQuoteData_QtType_RawValue(OBJECT_QUOTEQuoteData *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTEQuoteData's @c trdStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEQuoteData_TrdStatus_RawValue(OBJECT_QUOTEQuoteData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEQuoteData's @c trdStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEQuoteData_TrdStatus_RawValue(OBJECT_QUOTEQuoteData *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTEQuoteData's @c usTime property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEQuoteData_UsTime_RawValue(OBJECT_QUOTEQuoteData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEQuoteData's @c usTime property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEQuoteData_UsTime_RawValue(OBJECT_QUOTEQuoteData *message, int32_t value);

#pragma mark - OBJECT_QUOTEIndexQuoteData

typedef GPB_ENUM(OBJECT_QUOTEIndexQuoteData_FieldNumber) {
  OBJECT_QUOTEIndexQuoteData_FieldNumber_Up = 1,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_Unchange = 2,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_Down = 3,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_MktCap = 4,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_FloatCap = 5,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_Pe = 6,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_PeTtm = 7,
  OBJECT_QUOTEIndexQuoteData_FieldNumber_Pb = 8,
};

GPB_FINAL @interface OBJECT_QUOTEIndexQuoteData : GPBMessage

/** 涨家数 */
@property(nonatomic, readwrite) uint32_t up;

/** 平家数，包括停牌 */
@property(nonatomic, readwrite) uint32_t unchange;

/** 跌家数 */
@property(nonatomic, readwrite) uint32_t down;

/** 总市值 */
@property(nonatomic, readwrite) int64_t mktCap;

/** 流通市值 */
@property(nonatomic, readwrite) int64_t floatCap;

/** 盘口优化新增 */
@property(nonatomic, readwrite) int32_t pe;

/** TTM市盈率 */
@property(nonatomic, readwrite) int32_t peTtm;

/** 市净率 */
@property(nonatomic, readwrite) int32_t pb;

@end

#pragma mark - OBJECT_QUOTEStockQuoteData

typedef GPB_ENUM(OBJECT_QUOTEStockQuoteData_FieldNumber) {
  OBJECT_QUOTEStockQuoteData_FieldNumber_In_p = 1,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Out_p = 2,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Pe = 3,
  OBJECT_QUOTEStockQuoteData_FieldNumber_PeTtm = 4,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Pb = 5,
  OBJECT_QUOTEStockQuoteData_FieldNumber_DivYield = 6,
  OBJECT_QUOTEStockQuoteData_FieldNumber_MktCap = 7,
  OBJECT_QUOTEStockQuoteData_FieldNumber_FloatCap = 8,
  OBJECT_QUOTEStockQuoteData_FieldNumber_AhQt = 9,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Cas = 10,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Vcm = 11,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Adrh = 12,
  OBJECT_QUOTEStockQuoteData_FieldNumber_Ps = 13,
};

GPB_FINAL @interface OBJECT_QUOTEStockQuoteData : GPBMessage

/** 内盘 */
@property(nonatomic, readwrite) uint64_t in_p;

/** 外盘 */
@property(nonatomic, readwrite) uint64_t out_p;

/** 市盈率 */
@property(nonatomic, readwrite) int32_t pe;

/** TTM市盈率 */
@property(nonatomic, readwrite) int32_t peTtm;

/** 市净率 */
@property(nonatomic, readwrite) int32_t pb;

/** 股息率 */
@property(nonatomic, readwrite) int32_t divYield;

/** 总市值 */
@property(nonatomic, readwrite) int64_t mktCap;

/** 流通市值 */
@property(nonatomic, readwrite) int64_t floatCap;

/** AH关联信息 */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEAHQuote *ahQt;
/** Test to see if @c ahQt has been set. */
@property(nonatomic, readwrite) BOOL hasAhQt;

/** CAS */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECASQuote *cas;
/** Test to see if @c cas has been set. */
@property(nonatomic, readwrite) BOOL hasCas;

/** VCM */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEVCMQuote *vcm;
/** Test to see if @c vcm has been set. */
@property(nonatomic, readwrite) BOOL hasVcm;

/** 港股ADR关联行情信息(一级二级ADR,非高级) */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEADRHQuote *adrh;
/** Test to see if @c adrh has been set. */
@property(nonatomic, readwrite) BOOL hasAdrh;

/** 市销率 */
@property(nonatomic, readwrite) int32_t ps;

@end

#pragma mark - OBJECT_QUOTEFundQuoteData

typedef GPB_ENUM(OBJECT_QUOTEFundQuoteData_FieldNumber) {
  OBJECT_QUOTEFundQuoteData_FieldNumber_In_p = 1,
  OBJECT_QUOTEFundQuoteData_FieldNumber_Out_p = 2,
  OBJECT_QUOTEFundQuoteData_FieldNumber_Premium = 3,
  OBJECT_QUOTEFundQuoteData_FieldNumber_MktCap = 4,
  OBJECT_QUOTEFundQuoteData_FieldNumber_FloatCap = 5,
  OBJECT_QUOTEFundQuoteData_FieldNumber_Cas = 8,
  OBJECT_QUOTEFundQuoteData_FieldNumber_Vcm = 9,
  OBJECT_QUOTEFundQuoteData_FieldNumber_Pe = 10,
  OBJECT_QUOTEFundQuoteData_FieldNumber_PeTtm = 11,
  OBJECT_QUOTEFundQuoteData_FieldNumber_Pb = 12,
  OBJECT_QUOTEFundQuoteData_FieldNumber_DivYield = 13,
};

GPB_FINAL @interface OBJECT_QUOTEFundQuoteData : GPBMessage

/** 内盘 */
@property(nonatomic, readwrite) uint64_t in_p;

/** 外盘 */
@property(nonatomic, readwrite) uint64_t out_p;

/** 基金溢价,使用时除以 100 */
@property(nonatomic, readwrite) int32_t premium;

/** 总市值 */
@property(nonatomic, readwrite) int64_t mktCap;

/** 流通市值 */
@property(nonatomic, readwrite) int64_t floatCap;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTECASQuote *cas;
/** Test to see if @c cas has been set. */
@property(nonatomic, readwrite) BOOL hasCas;

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEVCMQuote *vcm;
/** Test to see if @c vcm has been set. */
@property(nonatomic, readwrite) BOOL hasVcm;

/** 盘口优化新增 */
@property(nonatomic, readwrite) int32_t pe;

/** TTM市盈率 */
@property(nonatomic, readwrite) int32_t peTtm;

/** 市净率 */
@property(nonatomic, readwrite) int32_t pb;

/** 股息率 */
@property(nonatomic, readwrite) int32_t divYield;

@end

#pragma mark - OBJECT_QUOTEBondQuoteData

typedef GPB_ENUM(OBJECT_QUOTEBondQuoteData_FieldNumber) {
  OBJECT_QUOTEBondQuoteData_FieldNumber_In_p = 1,
  OBJECT_QUOTEBondQuoteData_FieldNumber_Out_p = 2,
  OBJECT_QUOTEBondQuoteData_FieldNumber_MktCap = 3,
  OBJECT_QUOTEBondQuoteData_FieldNumber_FloatCap = 4,
};

GPB_FINAL @interface OBJECT_QUOTEBondQuoteData : GPBMessage

/** 内盘 */
@property(nonatomic, readwrite) uint64_t in_p;

/** 外盘 */
@property(nonatomic, readwrite) uint64_t out_p;

/** 总市值 */
@property(nonatomic, readwrite) int64_t mktCap;

/** 流通市值 */
@property(nonatomic, readwrite) int64_t floatCap;

@end

#pragma mark - OBJECT_QUOTEOptionQuoteData

typedef GPB_ENUM(OBJECT_QUOTEOptionQuoteData_FieldNumber) {
  OBJECT_QUOTEOptionQuoteData_FieldNumber_Premium = 1,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_ImpliedVolatility = 2,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_Delta = 3,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_Gamma = 4,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_Theta = 5,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_Vega = 6,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_Rho = 7,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_OpenInt = 8,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_TheoryPrice = 9,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_BreakevenPoint = 10,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_InValue = 11,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_TimeValue = 12,
  OBJECT_QUOTEOptionQuoteData_FieldNumber_RemainingTime = 13,
};

GPB_FINAL @interface OBJECT_QUOTEOptionQuoteData : GPBMessage

/** 溢价,使用时除以 100 */
@property(nonatomic, readwrite) int32_t premium;

/** 引申波幅 */
@property(nonatomic, readwrite) int32_t impliedVolatility;

/** 对冲值 */
@property(nonatomic, readwrite) int32_t delta;

/** Gamma(Delta变化/标的资产价格变化；期权价格对标的资产价格的二阶导数) */
@property(nonatomic, readwrite) int32_t gamma;

/** Theta(期权价格变化/期权有效期变化；期权价格对时间的一阶导数) */
@property(nonatomic, readwrite) int32_t theta;

/** Vega(期权价格变化/标的资产价格波动率的变化；期权价格对波动率的一阶导数) */
@property(nonatomic, readwrite) int32_t vega;

/** Rho（期权价格变化/利率变化；期权价格对无风险利率的一阶导数） */
@property(nonatomic, readwrite) int32_t rho;

/** 未平仓数 */
@property(nonatomic, readwrite) uint64_t openInt;

/** 期权理论价格 */
@property(nonatomic, readwrite) int64_t theoryPrice;

/** 打和点 */
@property(nonatomic, readwrite) int64_t breakevenPoint;

/** 内在价值 */
@property(nonatomic, readwrite) int64_t inValue;

/** 时间价值 */
@property(nonatomic, readwrite) int64_t timeValue;

/** 据到期日还有多少天 */
@property(nonatomic, readwrite) int32_t remainingTime;

@end

#pragma mark - OBJECT_QUOTEWarrantQuoteData

typedef GPB_ENUM(OBJECT_QUOTEWarrantQuoteData_FieldNumber) {
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_In_p = 1,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_Out_p = 2,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_WrnType = 3,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_Premium = 4,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_ImpliedVolatility = 5,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_Delta = 6,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_Moneyness = 7,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_Gearing = 8,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_Effgearing = 9,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_DiffRatio = 10,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_ConvertPrice = 11,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_BreakevenPoint = 12,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_FromUpper = 13,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_FromLower = 14,
  OBJECT_QUOTEWarrantQuoteData_FieldNumber_UnderlingQt = 20,
};

GPB_FINAL @interface OBJECT_QUOTEWarrantQuoteData : GPBMessage

/** 内盘 */
@property(nonatomic, readwrite) uint64_t in_p;

/** 外盘 */
@property(nonatomic, readwrite) uint64_t out_p;

@property(nonatomic, readwrite) OBJECT_QUOTEWarrantType wrnType;

/** 溢价,使用时除以 100 */
@property(nonatomic, readwrite) int32_t premium;

/** 引申波幅 */
@property(nonatomic, readwrite) int32_t impliedVolatility;

/** 对冲值 */
@property(nonatomic, readwrite) int32_t delta;

/** 价值状况 */
@property(nonatomic, readwrite) int32_t moneyness;

/** 杠杆比率 */
@property(nonatomic, readwrite) int32_t gearing;

/** 有效杠杆 */
@property(nonatomic, readwrite) int32_t effgearing;

/** 正股价距离收回价比率 使用 =  diffRatio / 10000 */
@property(nonatomic, readwrite) int32_t diffRatio;

/** 换股价：最新价 * 换股比率 */
@property(nonatomic, readwrite) int64_t convertPrice;

/** 打和点 */
@property(nonatomic, readwrite) int32_t breakevenPoint;

/** 距上限价 除以100(%) */
@property(nonatomic, readwrite) int32_t fromUpper;

/** 距下限价 除以100(%) */
@property(nonatomic, readwrite) int32_t fromLower;

/** 关联正股 */
@property(nonatomic, readwrite, strong, null_resettable) OBJECT_QUOTEUnderlyingQuote *underlingQt;
/** Test to see if @c underlingQt has been set. */
@property(nonatomic, readwrite) BOOL hasUnderlingQt;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEWarrantQuoteData's @c wrnType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEWarrantQuoteData_WrnType_RawValue(OBJECT_QUOTEWarrantQuoteData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEWarrantQuoteData's @c wrnType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEWarrantQuoteData_WrnType_RawValue(OBJECT_QUOTEWarrantQuoteData *message, int32_t value);

#pragma mark - OBJECT_QUOTESectorQuoteData

typedef GPB_ENUM(OBJECT_QUOTESectorQuoteData_FieldNumber) {
  OBJECT_QUOTESectorQuoteData_FieldNumber_Up = 1,
  OBJECT_QUOTESectorQuoteData_FieldNumber_Unchange = 2,
  OBJECT_QUOTESectorQuoteData_FieldNumber_Down = 3,
  OBJECT_QUOTESectorQuoteData_FieldNumber_MktCap = 4,
  OBJECT_QUOTESectorQuoteData_FieldNumber_FloatCap = 5,
  OBJECT_QUOTESectorQuoteData_FieldNumber_Pe = 6,
  OBJECT_QUOTESectorQuoteData_FieldNumber_PeTtm = 7,
  OBJECT_QUOTESectorQuoteData_FieldNumber_Pb = 8,
};

GPB_FINAL @interface OBJECT_QUOTESectorQuoteData : GPBMessage

/** 涨家数 */
@property(nonatomic, readwrite) uint32_t up;

/** 平家数，包括停牌 */
@property(nonatomic, readwrite) uint32_t unchange;

/** 跌家数 */
@property(nonatomic, readwrite) uint32_t down;

/** 总市值 */
@property(nonatomic, readwrite) int64_t mktCap;

/** 流通市值 */
@property(nonatomic, readwrite) int64_t floatCap;

/** 盘口优化新增 */
@property(nonatomic, readwrite) int32_t pe;

/** TTM市盈率 */
@property(nonatomic, readwrite) int32_t peTtm;

/** 市净率 */
@property(nonatomic, readwrite) int32_t pb;

@end

#pragma mark - OBJECT_QUOTESimpleQuote

typedef GPB_ENUM(OBJECT_QUOTESimpleQuote_FieldNumber) {
  OBJECT_QUOTESimpleQuote_FieldNumber_Seq = 1,
  OBJECT_QUOTESimpleQuote_FieldNumber_LatestTime = 2,
  OBJECT_QUOTESimpleQuote_FieldNumber_LatestPrice = 3,
  OBJECT_QUOTESimpleQuote_FieldNumber_Netchng = 4,
  OBJECT_QUOTESimpleQuote_FieldNumber_Pctchng = 5,
  OBJECT_QUOTESimpleQuote_FieldNumber_MktStatus = 6,
  OBJECT_QUOTESimpleQuote_FieldNumber_TrdStatus = 7,
  OBJECT_QUOTESimpleQuote_FieldNumber_QtType = 8,
  OBJECT_QUOTESimpleQuote_FieldNumber_High = 9,
  OBJECT_QUOTESimpleQuote_FieldNumber_Low = 10,
  OBJECT_QUOTESimpleQuote_FieldNumber_Volume = 11,
  OBJECT_QUOTESimpleQuote_FieldNumber_Amount = 12,
};

GPB_FINAL @interface OBJECT_QUOTESimpleQuote : GPBMessage

/** 行情序号 */
@property(nonatomic, readwrite) uint32_t seq;

/** 市场行情时间 YYYYMMDDHHMMSSss */
@property(nonatomic, readwrite) uint64_t latestTime;

/** 最新价 */
@property(nonatomic, readwrite) int64_t latestPrice;

/** 涨跌值 */
@property(nonatomic, readwrite) int64_t netchng;

/** 涨跌幅, 使用时除以 100 */
@property(nonatomic, readwrite) int32_t pctchng;

/** 市场状态 */
@property(nonatomic, readwrite) enum OBJECT_MARKETMarketStatus mktStatus;

/** 个股交易状态 */
@property(nonatomic, readwrite) OBJECT_QUOTETradingStatus trdStatus;

/** 行情类别，决定读取后面哪个数据字段 */
@property(nonatomic, readwrite) OBJECT_QUOTEQuoteType qtType;

/** 最高价 */
@property(nonatomic, readwrite) int64_t high;

/** 最低价 */
@property(nonatomic, readwrite) int64_t low;

/** 总成交量 */
@property(nonatomic, readwrite) uint64_t volume;

/** 总成交金额 */
@property(nonatomic, readwrite) int64_t amount;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTESimpleQuote's @c mktStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTESimpleQuote_MktStatus_RawValue(OBJECT_QUOTESimpleQuote *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTESimpleQuote's @c mktStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTESimpleQuote_MktStatus_RawValue(OBJECT_QUOTESimpleQuote *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTESimpleQuote's @c trdStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTESimpleQuote_TrdStatus_RawValue(OBJECT_QUOTESimpleQuote *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTESimpleQuote's @c trdStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTESimpleQuote_TrdStatus_RawValue(OBJECT_QUOTESimpleQuote *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTESimpleQuote's @c qtType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTESimpleQuote_QtType_RawValue(OBJECT_QUOTESimpleQuote *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTESimpleQuote's @c qtType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTESimpleQuote_QtType_RawValue(OBJECT_QUOTESimpleQuote *message, int32_t value);

#pragma mark - OBJECT_QUOTEOrder

typedef GPB_ENUM(OBJECT_QUOTEOrder_FieldNumber) {
  OBJECT_QUOTEOrder_FieldNumber_Price = 1,
  OBJECT_QUOTEOrder_FieldNumber_Size = 2,
  OBJECT_QUOTEOrder_FieldNumber_Id_p = 3,
};

GPB_FINAL @interface OBJECT_QUOTEOrder : GPBMessage

@property(nonatomic, readwrite) int64_t price;

/** order size or total order size depending on from OrderBook.merge_flag */
@property(nonatomic, readwrite) int64_t size;

/** debugging purpose, only set if merge_flag is false */
@property(nonatomic, readwrite) int64_t id_p;

@end

#pragma mark - OBJECT_QUOTEOrderBook

typedef GPB_ENUM(OBJECT_QUOTEOrderBook_FieldNumber) {
  OBJECT_QUOTEOrderBook_FieldNumber_Id_p = 1,
  OBJECT_QUOTEOrderBook_FieldNumber_AskArray = 2,
  OBJECT_QUOTEOrderBook_FieldNumber_BidArray = 3,
  OBJECT_QUOTEOrderBook_FieldNumber_Time = 4,
  OBJECT_QUOTEOrderBook_FieldNumber_MergeFlag = 5,
  OBJECT_QUOTEOrderBook_FieldNumber_RecvTime = 6,
  OBJECT_QUOTEOrderBook_FieldNumber_SendTime = 7,
  OBJECT_QUOTEOrderBook_FieldNumber_PriceBase = 8,
};

GPB_FINAL @interface OBJECT_QUOTEOrderBook : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEOrder*> *askArray;
/** The number of items in @c askArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OBJECT_QUOTEOrder*> *bidArray;
/** The number of items in @c bidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidArray_Count;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL mergeFlag;

@property(nonatomic, readwrite) int64_t recvTime;

@property(nonatomic, readwrite) int64_t sendTime;

@property(nonatomic, readwrite) uint32_t priceBase;

@end

#pragma mark - OBJECT_QUOTECodeStatus

typedef GPB_ENUM(OBJECT_QUOTECodeStatus_FieldNumber) {
  OBJECT_QUOTECodeStatus_FieldNumber_Id_p = 1,
  OBJECT_QUOTECodeStatus_FieldNumber_Time = 2,
  OBJECT_QUOTECodeStatus_FieldNumber_TrdStatus = 3,
};

GPB_FINAL @interface OBJECT_QUOTECodeStatus : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) OBJECT_SECUFullID *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite) int64_t time;

/** 个股交易状态 */
@property(nonatomic, readwrite) OBJECT_QUOTETradingStatus trdStatus;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTECodeStatus's @c trdStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTECodeStatus_TrdStatus_RawValue(OBJECT_QUOTECodeStatus *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTECodeStatus's @c trdStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTECodeStatus_TrdStatus_RawValue(OBJECT_QUOTECodeStatus *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
