// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quota.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Quota.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - OBJECT_QUOTEQuotaRoot

@implementation OBJECT_QUOTEQuotaRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - OBJECT_QUOTEQuotaRoot_FileDescriptor

static GPBFileDescriptor *OBJECT_QUOTEQuotaRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"yx.quote.v2.object.quote"
                                                 objcPrefix:@"OBJECT_QUOTE"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum OBJECT_QUOTEQuotaScene

GPBEnumDescriptor *OBJECT_QUOTEQuotaScene_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "QuotaOneDay\000QuotaFiveDay\000";
    static const int32_t values[] = {
        OBJECT_QUOTEQuotaScene_QuotaOneDay,
        OBJECT_QUOTEQuotaScene_QuotaFiveDay,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(OBJECT_QUOTEQuotaScene)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:OBJECT_QUOTEQuotaScene_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL OBJECT_QUOTEQuotaScene_IsValidValue(int32_t value__) {
  switch (value__) {
    case OBJECT_QUOTEQuotaScene_QuotaOneDay:
    case OBJECT_QUOTEQuotaScene_QuotaFiveDay:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum OBJECT_QUOTEQuota_Status

GPBEnumDescriptor *OBJECT_QUOTEQuota_Status_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "AmountUnusable\000AmountSable\000";
    static const int32_t values[] = {
        OBJECT_QUOTEQuota_Status_AmountUnusable,
        OBJECT_QUOTEQuota_Status_AmountSable,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(OBJECT_QUOTEQuota_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:OBJECT_QUOTEQuota_Status_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL OBJECT_QUOTEQuota_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case OBJECT_QUOTEQuota_Status_AmountUnusable:
    case OBJECT_QUOTEQuota_Status_AmountSable:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum OBJECT_QUOTEQuota_Capflow

GPBEnumDescriptor *OBJECT_QUOTEQuota_Capflow_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "CapitalSb\000CapitalNb\000";
    static const int32_t values[] = {
        OBJECT_QUOTEQuota_Capflow_CapitalSb,
        OBJECT_QUOTEQuota_Capflow_CapitalNb,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(OBJECT_QUOTEQuota_Capflow)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:OBJECT_QUOTEQuota_Capflow_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL OBJECT_QUOTEQuota_Capflow_IsValidValue(int32_t value__) {
  switch (value__) {
    case OBJECT_QUOTEQuota_Capflow_CapitalSb:
    case OBJECT_QUOTEQuota_Capflow_CapitalNb:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - OBJECT_QUOTEQuotaData

@implementation OBJECT_QUOTEQuotaData

@dynamic time;
@dynamic thresholdAmount;
@dynamic posAmt;
@dynamic amountStatus;
@dynamic captialFlow;
@dynamic turnoverBuy;
@dynamic turnoverSel;
@dynamic netTurnover;

typedef struct OBJECT_QUOTEQuotaData__storage_ {
  uint32_t _has_storage_[1];
  OBJECT_QUOTEQuota_Status amountStatus;
  OBJECT_QUOTEQuota_Capflow captialFlow;
  int64_t time;
  int64_t thresholdAmount;
  int64_t posAmt;
  int64_t turnoverBuy;
  int64_t turnoverSel;
  int64_t netTurnover;
} OBJECT_QUOTEQuotaData__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_Time,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, time),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "thresholdAmount",
        .dataTypeSpecific.className = NULL,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_ThresholdAmount,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, thresholdAmount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "posAmt",
        .dataTypeSpecific.className = NULL,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_PosAmt,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, posAmt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "amountStatus",
        .dataTypeSpecific.enumDescFunc = OBJECT_QUOTEQuota_Status_EnumDescriptor,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_AmountStatus,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, amountStatus),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "captialFlow",
        .dataTypeSpecific.enumDescFunc = OBJECT_QUOTEQuota_Capflow_EnumDescriptor,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_CaptialFlow,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, captialFlow),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "turnoverBuy",
        .dataTypeSpecific.className = NULL,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_TurnoverBuy,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, turnoverBuy),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "turnoverSel",
        .dataTypeSpecific.className = NULL,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_TurnoverSel,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, turnoverSel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "netTurnover",
        .dataTypeSpecific.className = NULL,
        .number = OBJECT_QUOTEQuotaData_FieldNumber_NetTurnover,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(OBJECT_QUOTEQuotaData__storage_, netTurnover),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[OBJECT_QUOTEQuotaData class]
                                     rootClass:[OBJECT_QUOTEQuotaRoot class]
                                          file:OBJECT_QUOTEQuotaRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(OBJECT_QUOTEQuotaData__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\003\017\000\004\006\000\005\014\000\006\013\000\007\013\000\010\013\000\t\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t OBJECT_QUOTEQuotaData_AmountStatus_RawValue(OBJECT_QUOTEQuotaData *message) {
  GPBDescriptor *descriptor = [OBJECT_QUOTEQuotaData descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:OBJECT_QUOTEQuotaData_FieldNumber_AmountStatus];
  return GPBGetMessageInt32Field(message, field);
}

void SetOBJECT_QUOTEQuotaData_AmountStatus_RawValue(OBJECT_QUOTEQuotaData *message, int32_t value) {
  GPBDescriptor *descriptor = [OBJECT_QUOTEQuotaData descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:OBJECT_QUOTEQuotaData_FieldNumber_AmountStatus];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t OBJECT_QUOTEQuotaData_CaptialFlow_RawValue(OBJECT_QUOTEQuotaData *message) {
  GPBDescriptor *descriptor = [OBJECT_QUOTEQuotaData descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:OBJECT_QUOTEQuotaData_FieldNumber_CaptialFlow];
  return GPBGetMessageInt32Field(message, field);
}

void SetOBJECT_QUOTEQuotaData_CaptialFlow_RawValue(OBJECT_QUOTEQuotaData *message, int32_t value) {
  GPBDescriptor *descriptor = [OBJECT_QUOTEQuotaData descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:OBJECT_QUOTEQuotaData_FieldNumber_CaptialFlow];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
