// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object/quote/scm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum OBJECT_QUOTEScmScene

/** 港股通额度使用场景 */
typedef GPB_ENUM(OBJECT_QUOTEScmScene) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEScmScene_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 当日分时 */
  OBJECT_QUOTEScmScene_QuotaOneDay = 0,

  /** 五日分时 */
  OBJECT_QUOTEScmScene_QuotaFiveDay = 1,
};

GPBEnumDescriptor *OBJECT_QUOTEScmScene_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEScmScene_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEScmStatus

/** 额度状态 */
typedef GPB_ENUM(OBJECT_QUOTEScmStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEScmStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 额度不可用 */
  OBJECT_QUOTEScmStatus_AmountUnusable = 0,

  /** 额度可用 */
  OBJECT_QUOTEScmStatus_AmountSable = 1,
};

GPBEnumDescriptor *OBJECT_QUOTEScmStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEScmStatus_IsValidValue(int32_t value);

#pragma mark - Enum OBJECT_QUOTEScmCapflow

/** 资金流向 */
typedef GPB_ENUM(OBJECT_QUOTEScmCapflow) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OBJECT_QUOTEScmCapflow_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 南下 */
  OBJECT_QUOTEScmCapflow_CapitalSb = 0,

  /** 北上 */
  OBJECT_QUOTEScmCapflow_CapitalNb = 1,
};

GPBEnumDescriptor *OBJECT_QUOTEScmCapflow_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OBJECT_QUOTEScmCapflow_IsValidValue(int32_t value);

#pragma mark - OBJECT_QUOTEScmRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OBJECT_QUOTEScmRoot : GPBRootObject
@end

#pragma mark - OBJECT_QUOTEScmData

typedef GPB_ENUM(OBJECT_QUOTEScmData_FieldNumber) {
  OBJECT_QUOTEScmData_FieldNumber_Time = 2,
  OBJECT_QUOTEScmData_FieldNumber_ThresholdAmount = 3,
  OBJECT_QUOTEScmData_FieldNumber_PosAmt = 4,
  OBJECT_QUOTEScmData_FieldNumber_AmountStatus = 5,
  OBJECT_QUOTEScmData_FieldNumber_CaptialFlow = 6,
  OBJECT_QUOTEScmData_FieldNumber_TurnoverBuy = 7,
  OBJECT_QUOTEScmData_FieldNumber_TurnoverSel = 8,
  OBJECT_QUOTEScmData_FieldNumber_NetTurnover = 9,
};

GPB_FINAL @interface OBJECT_QUOTEScmData : GPBMessage

/** 当前时间 */
@property(nonatomic, readwrite) int64_t time;

/** 每日初始额度 */
@property(nonatomic, readwrite) int64_t thresholdAmount;

/** 日中剩余额度 */
@property(nonatomic, readwrite) int64_t posAmt;

/** 额度状态 */
@property(nonatomic, readwrite) OBJECT_QUOTEScmStatus amountStatus;

/** 资金流向 */
@property(nonatomic, readwrite) OBJECT_QUOTEScmCapflow captialFlow;

/** 买成交额，对应港交所81号消息 */
@property(nonatomic, readwrite) int64_t turnoverBuy;

/** 卖成交额 */
@property(nonatomic, readwrite) int64_t turnoverSel;

/** 净成交额 */
@property(nonatomic, readwrite) int64_t netTurnover;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEScmData's @c amountStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEScmData_AmountStatus_RawValue(OBJECT_QUOTEScmData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEScmData's @c amountStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEScmData_AmountStatus_RawValue(OBJECT_QUOTEScmData *message, int32_t value);

/**
 * Fetches the raw value of a @c OBJECT_QUOTEScmData's @c captialFlow property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEScmData_CaptialFlow_RawValue(OBJECT_QUOTEScmData *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEScmData's @c captialFlow property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEScmData_CaptialFlow_RawValue(OBJECT_QUOTEScmData *message, int32_t value);

#pragma mark - OBJECT_QUOTEScmKline

typedef GPB_ENUM(OBJECT_QUOTEScmKline_FieldNumber) {
  OBJECT_QUOTEScmKline_FieldNumber_Cycletime = 1,
  OBJECT_QUOTEScmKline_FieldNumber_CaptialFlow = 2,
  OBJECT_QUOTEScmKline_FieldNumber_Worth = 3,
};

GPB_FINAL @interface OBJECT_QUOTEScmKline : GPBMessage

/** 周期时间 */
@property(nonatomic, readwrite) int64_t cycletime;

/** 资金流向 */
@property(nonatomic, readwrite) OBJECT_QUOTEScmCapflow captialFlow;

/** 周期内资金净值 */
@property(nonatomic, readwrite) int64_t worth;

@end

/**
 * Fetches the raw value of a @c OBJECT_QUOTEScmKline's @c captialFlow property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t OBJECT_QUOTEScmKline_CaptialFlow_RawValue(OBJECT_QUOTEScmKline *message);
/**
 * Sets the raw value of an @c OBJECT_QUOTEScmKline's @c captialFlow property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetOBJECT_QUOTEScmKline_CaptialFlow_RawValue(OBJECT_QUOTEScmKline *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
